enum StatusType {
  Speeder,
  Power,
  Magica,
  Balance,
  God,
}

enum CartType {
  Battle = 'battle',
  Support = 'support',
}

export enum Rarity {
  Common = 'common',
  Uncommon = 'uncommon',
  Rare = 'rare',
  SuperRare = 'superRare',
  UltraRare = 'ultraRare',
  LegendRare = 'legendRare',
}

interface CharacterData {
  characterId: number;
  statusType: StatusType;
  rarity: Rarity;
  fileName: string;
  cardType: CartType;
}

interface CharacterBaseData {
  characterId: number;
  jaName: string;
  kanaName: string;
}

export const MonsterBaseData = [
  {
    monsterId: 1,
    jaName: 'キマイラ',
    kanaName: 'キマイラ',
  },
  {
    monsterId: 2,
    jaName: '黄金鉱龍 レゲンダ・アウレリア',
    kanaName: 'オウゴンコウリュウ レゲンダ アウレリア',
  },
  {
    monsterId: 3,
    jaName: '虹龍 スー・アムルゼス',
    kanaName: 'コウリュウ スー アムルゼス',
  },
  {
    monsterId: 4,
    jaName: '霊火 イリス・アレイオーン',
    kanaName: 'レイビ イリス アレイオーン',
  },
  {
    monsterId: 5,
    jaName: '節棍龍 リヴァイアサン',
    kanaName: 'セツコンリュウ リヴァイアサン',
  },
  {
    monsterId: 6,
    jaName: '木晶 クグノチ',
    kanaName: 'モクショウ クグノチ',
  },
  {
    monsterId: 7,
    jaName: 'コンバット・マークⅡ',
    kanaName: 'コンバット・マークⅡ',
  },
  {
    monsterId: 8,
    jaName: '監視神 メタトロン',
    kanaName: 'カンシカン メタトロン',
  },
  {
    monsterId: 9,
    jaName: '泥欲塊 コスモス',
    kanaName: 'デイヨクカイ コスモス',
  },
  {
    monsterId: 10,
    jaName: '鉱神 ベリル',
    kanaName: 'コウジン ベリル',
  },
  {
    monsterId: 11,
    jaName: '花龍 リントヴルム',
    kanaName: 'カリュウ リントヴルム',
  },
  {
    monsterId: 12,
    jaName: '魔獣 スヴァジルファリ',
    kanaName: 'カリュウ リントヴルム',
  },
  {
    monsterId: 13,
    jaName: '白鯨王 ケートゥス・ボルカ',
    kanaName: 'ハクゲイオウ ケートゥス ボルカ',
  },
];

export const MonsterData = [
  {
    monsterId: 1,
    statusType: StatusType.Magica,
    rarity: Rarity.Common,
    fileName: 'f116',
    cardType: CartType.Battle,
  },
  {
    monsterId: 1,
    statusType: StatusType.Magica,
    rarity: Rarity.Common,
    fileName: 'f117',
    cardType: CartType.Battle,
  },
  {
    monsterId: 1,
    statusType: StatusType.Magica,
    rarity: Rarity.Common,
    fileName: 'f118',
    cardType: CartType.Battle,
  },
  {
    monsterId: 2,
    statusType: StatusType.God,
    rarity: Rarity.SuperRare,
    fileName: 'f181',
    cardType: CartType.Battle,
  },
  {
    monsterId: 2,
    statusType: StatusType.God,
    rarity: Rarity.UltraRare,
    fileName: 'f182',
    cardType: CartType.Battle,
  },
  {
    monsterId: 2,
    statusType: StatusType.God,
    rarity: Rarity.LegendRare,
    fileName: 'f183',
    cardType: CartType.Battle,
  },
  {
    monsterId: 3,
    statusType: StatusType.God,
    rarity: Rarity.SuperRare,
    fileName: 'f184',
    cardType: CartType.Battle,
  },
  {
    monsterId: 3,
    statusType: StatusType.God,
    rarity: Rarity.UltraRare,
    fileName: 'f185',
    cardType: CartType.Battle,
  },
  {
    monsterId: 3,
    statusType: StatusType.God,
    rarity: Rarity.LegendRare,
    fileName: 'f186',
    cardType: CartType.Battle,
  },
  {
    monsterId: 4,
    statusType: StatusType.God,
    rarity: Rarity.SuperRare,
    fileName: 'f187',
    cardType: CartType.Battle,
  },
  {
    monsterId: 4,
    statusType: StatusType.God,
    rarity: Rarity.UltraRare,
    fileName: 'f188',
    cardType: CartType.Battle,
  },
  {
    monsterId: 4,
    statusType: StatusType.God,
    rarity: Rarity.LegendRare,
    fileName: 'f189',
    cardType: CartType.Battle,
  },
  {
    monsterId: 5,
    statusType: StatusType.God,
    rarity: Rarity.SuperRare,
    fileName: 'f190',
    cardType: CartType.Battle,
  },
  {
    monsterId: 5,
    statusType: StatusType.God,
    rarity: Rarity.UltraRare,
    fileName: 'f191',
    cardType: CartType.Battle,
  },
  {
    monsterId: 5,
    statusType: StatusType.God,
    rarity: Rarity.LegendRare,
    fileName: 'f192',
    cardType: CartType.Battle,
  },
  {
    monsterId: 6,
    statusType: StatusType.God,
    rarity: Rarity.SuperRare,
    fileName: 'f193',
    cardType: CartType.Battle,
  },
  {
    monsterId: 6,
    statusType: StatusType.God,
    rarity: Rarity.UltraRare,
    fileName: 'f194',
    cardType: CartType.Battle,
  },
  {
    monsterId: 6,
    statusType: StatusType.God,
    rarity: Rarity.LegendRare,
    fileName: 'f195',
    cardType: CartType.Battle,
  },
  {
    monsterId: 7,
    statusType: StatusType.God,
    rarity: Rarity.SuperRare,
    fileName: 'f196',
    cardType: CartType.Battle,
  },
  {
    monsterId: 7,
    statusType: StatusType.God,
    rarity: Rarity.UltraRare,
    fileName: 'f197',
    cardType: CartType.Battle,
  },
  {
    monsterId: 7,
    statusType: StatusType.God,
    rarity: Rarity.LegendRare,
    fileName: 'f198',
    cardType: CartType.Battle,
  },
  {
    monsterId: 8,
    statusType: StatusType.God,
    rarity: Rarity.SuperRare,
    fileName: 'f199',
    cardType: CartType.Battle,
  },
  {
    monsterId: 8,
    statusType: StatusType.God,
    rarity: Rarity.UltraRare,
    fileName: 'f200',
    cardType: CartType.Battle,
  },
  {
    monsterId: 8,
    statusType: StatusType.God,
    rarity: Rarity.LegendRare,
    fileName: 'f201',
    cardType: CartType.Battle,
  },
  {
    monsterId: 9,
    statusType: StatusType.God,
    rarity: Rarity.SuperRare,
    fileName: 'f202',
    cardType: CartType.Battle,
  },
  {
    monsterId: 9,
    statusType: StatusType.God,
    rarity: Rarity.UltraRare,
    fileName: 'f203',
    cardType: CartType.Battle,
  },
  {
    monsterId: 9,
    statusType: StatusType.God,
    rarity: Rarity.LegendRare,
    fileName: 'f204',
    cardType: CartType.Battle,
  },
  {
    monsterId: 10,
    statusType: StatusType.God,
    rarity: Rarity.SuperRare,
    fileName: 'f205',
    cardType: CartType.Battle,
  },
  {
    monsterId: 10,
    statusType: StatusType.God,
    rarity: Rarity.UltraRare,
    fileName: 'f206',
    cardType: CartType.Battle,
  },
  {
    monsterId: 10,
    statusType: StatusType.God,
    rarity: Rarity.LegendRare,
    fileName: 'f207',
    cardType: CartType.Battle,
  },
  {
    monsterId: 11,
    statusType: StatusType.God,
    rarity: Rarity.SuperRare,
    fileName: 'f269',
    cardType: CartType.Battle,
  },
  {
    monsterId: 11,
    statusType: StatusType.God,
    rarity: Rarity.UltraRare,
    fileName: 'f270',
    cardType: CartType.Battle,
  },
  {
    monsterId: 11,
    statusType: StatusType.God,
    rarity: Rarity.LegendRare,
    fileName: 'f271',
    cardType: CartType.Battle,
  },
  {
    monsterId: 12,
    statusType: StatusType.God,
    rarity: Rarity.SuperRare,
    fileName: 'f272',
    cardType: CartType.Battle,
  },
  {
    monsterId: 12,
    statusType: StatusType.God,
    rarity: Rarity.UltraRare,
    fileName: 'f273',
    cardType: CartType.Battle,
  },
  {
    monsterId: 12,
    statusType: StatusType.God,
    rarity: Rarity.LegendRare,
    fileName: 'f274',
    cardType: CartType.Battle,
  },
  {
    monsterId: 13,
    statusType: StatusType.God,
    rarity: Rarity.SuperRare,
    fileName: 'f275',
    cardType: CartType.Battle,
  },
  {
    monsterId: 13,
    statusType: StatusType.God,
    rarity: Rarity.UltraRare,
    fileName: 'f276',
    cardType: CartType.Battle,
  },
  {
    monsterId: 13,
    statusType: StatusType.God,
    rarity: Rarity.LegendRare,
    fileName: 'f277',
    cardType: CartType.Battle,
  },
];

export const CharacterBaseData: CharacterBaseData[] = [
  {
    characterId: 1,
    jaName: '司馬 青',
    kanaName: 'シバ アオ',
  },
  {
    characterId: 2,
    jaName: '紅 桃香',
    kanaName: 'クレナイ モモカ',
  },
  {
    characterId: 3,
    jaName: '三日月 トウジ',
    kanaName: 'ミカヅキ トウジ',
  },
  {
    characterId: 4,
    jaName: '飛騨 龍元',
    kanaName: 'ヒダ リュウゲン',
  },
  {
    characterId: 5,
    jaName: '三田 輪廻',
    kanaName: 'ミタ リンネ',
  },
  {
    characterId: 6,
    jaName: '由紀',
    kanaName: 'ユキ',
  },
  {
    characterId: 7,
    jaName: '島霧 かや',
    kanaName: 'トウギリ カヤ',
  },
  {
    characterId: 8,
    jaName: '御堂 虎丸',
    kanaName: 'ミドウ トラマル',
  },
  {
    characterId: 9,
    jaName: 'リーバッハ・イーリス',
    kanaName: 'リーバッハ イーリス',
  },
  {
    characterId: 10,
    jaName: '稲荷 オリビアライト',
    kanaName: 'イナリ オリビアライト',
  },
  {
    characterId: 11,
    jaName: '城田 トーラス',
    kanaName: 'シロタ トーラス',
  },
  {
    characterId: 12,
    jaName: '薬師 バラドック',
    kanaName: 'ヤクシ バラドック',
  },
  {
    characterId: 13,
    jaName: '黒蠍',
    kanaName: 'クロサソリ',
  },
  {
    characterId: 14,
    jaName: 'ロゼッタ',
    kanaName: 'ロゼッタ',
  },
  {
    characterId: 15,
    jaName: '夜月 夕',
    kanaName: 'ヤゲツ ユウ',
  },
  {
    characterId: 16,
    jaName: 'トト',
    kanaName: 'トト',
  },
  {
    characterId: 17,
    jaName: '卜部 トト',
    kanaName: 'ウラベ トト',
  },
  {
    characterId: 18,
    jaName: '髑髏 トマト',
    kanaName: 'ドクロ トマト',
  },
  {
    characterId: 19,
    jaName: '緑山 須佐',
    kanaName: 'ミドリヤマ スサ',
  },
  {
    characterId: 20,
    jaName: 'ミミ',
    kanaName: 'ミミ',
  },
  {
    characterId: 21,
    jaName: '青空 ミミ',
    kanaName: 'アオゾラ ミミ',
  },
  {
    characterId: 22,
    jaName: '桜 凛',
    kanaName: 'サクラ リン',
  },
  {
    characterId: 23,
    jaName: '悟',
    kanaName: 'サトル',
  },
  {
    characterId: 24,
    jaName: 'まどか',
    kanaName: 'マドカ',
  },
  {
    characterId: 25,
    jaName: '日向 涙',
    kanaName: 'ヒュウガ ナミダ',
  },
  {
    characterId: 26,
    jaName: '音音 ミカ',
    kanaName: 'オトネ ミカ',
  },
  {
    characterId: 27,
    jaName: '黒滝 火火',
    kanaName: 'クロタキ ヒビ',
  },
  {
    characterId: 28,
    jaName: '黒服 Z',
    kanaName: 'クロフク Z',
  },
  {
    characterId: 29,
    jaName: '茶々 マリン',
    kanaName: 'チャチャ マリン',
  },
  {
    characterId: 30,
    jaName: '影蔵 友',
    kanaName: 'カゲクラ トモ',
  },
  {
    characterId: 31,
    jaName: 'キキ美',
    kanaName: 'キキミ',
  },
  {
    characterId: 32,
    jaName: '水瓶 良',
    kanaName: 'ミズガメ リョウ',
  },
  {
    characterId: 33,
    jaName: '白 羅羅',
    kanaName: 'ハク ララ',
  },
  {
    characterId: 34,
    jaName: 'ビュリューゼフ・クローリー',
    kanaName: 'ビュリューゼフ クローリー',
  },
  {
    characterId: 35,
    jaName: '朧 ルーン',
    kanaName: 'オボロ ルーン',
  },
  {
    characterId: 36,
    jaName: 'パンプキンキラー',
    kanaName: 'パンプキンキラー',
  },
  {
    characterId: 37,
    jaName: '蒼井 ラーバビット',
    kanaName: 'アオイ ラーバビット',
  },
  {
    characterId: 38,
    jaName: 'ジン・ミーリアス',
    kanaName: 'ジン ミーリアス',
  },
  {
    characterId: 39,
    jaName: '華 灯',
    kanaName: 'はな あかり',
  },
  {
    characterId: 40,
    jaName: '紫 瞳',
    kanaName: 'ムラサキ ヒトミ',
  },
  {
    characterId: 41,
    jaName: '薔薇 望',
    kanaName: 'バラ ノゾミ',
  },
  {
    characterId: 42,
    jaName: '林檎 リーヒビリア',
    kanaName: 'リンゴ リーヒビリア',
  },
  {
    characterId: 43,
    jaName: '狐 ララ',
    kanaName: 'キツネ ララ',
  },
  {
    characterId: 44,
    jaName: '狐 ナナ',
    kanaName: 'キツネ ナナ',
  },
  {
    characterId: 45,
    jaName: '星野 ミネルバ',
    kanaName: 'ホシノ ミネルバ',
  },
  {
    characterId: 46,
    jaName: 'ジャム・ビーリッヒ',
    kanaName: 'ジャム ビーリッヒ',
  },
  {
    characterId: 47,
    jaName: '港 ラプトル',
    kanaName: 'ミナト ラプトル',
  },
  {
    characterId: 48,
    jaName: '冠 誠',
    kanaName: 'カンムリ マコト',
  },
  {
    characterId: 49,
    jaName: '青山 マリ',
    kanaName: 'アオヤマ マリ',
  },
  {
    characterId: 50,
    jaName: 'エドワード・ザックニコフ',
    kanaName: 'エドワード ザックニコフ',
  },
  {
    characterId: 51,
    jaName: 'ミカ・サニティア',
    kanaName: 'ミカ サニティア',
  },
  {
    characterId: 52,
    jaName: '寺町 パレード',
    kanaName: 'テラマチ パレード',
  },
  {
    characterId: 53,
    jaName: '王楼 エイジ',
    kanaName: 'オウロウ エイジ',
  },
  {
    characterId: 54,
    jaName: '虎 モモコ',
    kanaName: 'トラ モモコ',
  },
  {
    characterId: 55,
    jaName: 'グラム・グリーン',
    kanaName: 'グラム グリーン',
  },
  {
    characterId: 56,
    jaName: '遠方 やちる',
    kanaName: 'トウガタ ヤチル',
  },
  {
    characterId: 57,
    jaName: '如月 みづき',
    kanaName: 'キサラギ ミヅキ',
  },
  {
    characterId: 58,
    jaName: 'イシス 中村',
    kanaName: 'イシス ナカムラ',
  },
  {
    characterId: 59,
    jaName: '神鳴 ケンジ',
    kanaName: 'カミナル ケンジ',
  },
  {
    characterId: 60,
    jaName: '入間 貞',
    kanaName: 'イルマ タダシ',
  },
  {
    characterId: 61,
    jaName: 'ウル',
    kanaName: 'ウル',
  },
  {
    characterId: 62,
    jaName: '上海 アメン',
    kanaName: 'カミウミ アメン',
  },
  {
    characterId: 63,
    jaName: '歌田 セシル',
    kanaName: 'ウタダ セシル',
  },
  {
    characterId: 64,
    jaName: '赤城 マリアンヌ',
    kanaName: 'セキジョウ マリアンヌ',
  },
  {
    characterId: 65,
    jaName: '秋山 澪子',
    kanaName: 'アキヤマ ミヨコ',
  },
  {
    characterId: 66,
    jaName: '忌部 影子',
    kanaName: 'インベ カゲコ',
  },
  {
    characterId: 67,
    jaName: '田中 律',
    kanaName: 'タナカ リツ',
  },
  {
    characterId: 68,
    jaName: '真白 リボン',
    kanaName: 'マシロ リボン',
  },
  {
    characterId: 69,
    jaName: 'マーガレット・ルーシー',
    kanaName: 'マーガレット ルーシー',
  },
  {
    characterId: 70,
    jaName: '琴風 紬',
    kanaName: 'コトカゼ ツムギ',
  },
  {
    characterId: 71,
    jaName: 'ミスラ 貴子',
    kanaName: 'ミスラ タカコ',
  },
  {
    characterId: 72,
    jaName: 'ホルホル',
    kanaName: 'ホルホル',
  },
  {
    characterId: 73,
    jaName: 'ホルス・ウィングバード・エア',
    kanaName: 'ホルス ウィングバード エア',
  },
  {
    characterId: 74,
    jaName: '鷲宮 羽実',
    kanaName: 'ワシミヤ ハネミ',
  },
  {
    characterId: 75,
    jaName: '成畑 美子',
    kanaName: 'ナリバタ ミコ',
  },
  {
    characterId: 76,
    jaName: '朱雀 光',
    kanaName: 'スザク ヒカリ',
  },
  {
    characterId: 77,
    jaName: '朱雀 大河',
    kanaName: 'スザク タイガ',
  },
  {
    characterId: 78,
    jaName: '王 ミントミリーガル',
    kanaName: 'オウ ミントミリーガル',
  },
  {
    characterId: 79,
    jaName: '王 プラムラートス',
    kanaName: 'オウ プラムラートス',
  },
  {
    characterId: 80,
    jaName: 'アガルタ・ローランド',
    kanaName: 'アガルタ ローランド',
  },
  {
    characterId: 81,
    jaName: '明治 真一',
    kanaName: 'メイジ シンイチ',
  },
  {
    characterId: 82,
    jaName: '勒斯 ギーニッヒ',
    kanaName: 'ロクシ ギーニッヒ',
  },
  {
    characterId: 83,
    jaName: '牛若 藍',
    kanaName: 'ウシワカ ラン',
  },
  {
    characterId: 84,
    jaName: '嬉々木 ミルチカ',
    kanaName: 'キキキ ミルチカ',
  },
  {
    characterId: 85,
    jaName: '新山 ちひろ',
    kanaName: 'ニイヤマ チヒロ',
  },
  {
    characterId: 86,
    jaName: '黒野 ユニ',
    kanaName: 'クロノ ユニ',
  },
  {
    characterId: 87,
    jaName: 'ミリシア・ジュリエッタ',
    kanaName: 'ミリシア ジュリエッタ',
  },
  {
    characterId: 88,
    jaName: '神威 棒太',
    kanaName: 'シンイ ボーダ',
  },
  {
    characterId: 89,
    jaName: '紫水 サファイア',
    kanaName: 'シスイ サファイア',
  },
  {
    characterId: 90,
    jaName: 'レア・クリスマン',
    kanaName: 'レア クリスマン',
  },
  {
    characterId: 91,
    jaName: '赤孔雀 グレア',
    kanaName: 'セキクジャク グレア',
  },
  {
    characterId: 92,
    jaName: '片岡 ウィル',
    kanaName: 'カタオカ ウィル',
  },
  {
    characterId: 93,
    jaName: '色間 パレット',
    kanaName: 'イロマ パレット',
  },
  {
    characterId: 94,
    jaName: '鏡 京子',
    kanaName: 'カガミ キョウコ',
  },
  {
    characterId: 95,
    jaName: 'ミラ・フューレ',
    kanaName: 'ミラ フューレ',
  },
  {
    characterId: 96,
    jaName: '織田 銀次',
    kanaName: 'オダ ギンジ',
  },
  {
    characterId: 97,
    jaName: '吉田 ノイ',
    kanaName: 'ヨシダ ノイ',
  },
  {
    characterId: 98,
    jaName: '長岡 レン',
    kanaName: 'ナガオカ レン',
  },
  {
    characterId: 99,
    jaName: '夜神 ツバサ',
    kanaName: 'ヤガミ ツバサ',
  },
  {
    characterId: 100,
    jaName: '七魅 静香',
    kanaName: 'ナナミ シズカ',
  },
  {
    characterId: 101,
    jaName: '息吹 ゆめみ',
    kanaName: 'イブキ ユメミ',
  },
  {
    characterId: 102,
    jaName: '猫宮 チサ',
    kanaName: 'ネコミヤ チサ',
  },
  {
    characterId: 103,
    jaName: 'クロス・アークバル',
    kanaName: 'クロス アークバル',
  },
  {
    characterId: 104,
    jaName: '笠風 スズカ',
    kanaName: 'カサカゼ スズカ',
  },
  {
    characterId: 105,
    jaName: '未羅 せせり',
    kanaName: 'ミラ セセリ',
  },
  {
    characterId: 106,
    jaName: 'フリギア・アッペルシール',
    kanaName: 'フリギア アッペルシール',
  },
  {
    characterId: 107,
    jaName: '挺 ギニアラ',
    kanaName: 'チョウ　ギニアラ',
  },
  {
    characterId: 108,
    jaName: '楽木 ミルドラ',
    kanaName: 'ガキ ミルドラ',
  },
  {
    characterId: 109,
    jaName: '庵 コスモ',
    kanaName: 'アン コスモ',
  },
  {
    characterId: 110,
    jaName: '翡翠 かおる',
    kanaName: 'ヒスイ カオル',
  },
  {
    characterId: 111,
    jaName: '炭山 心',
    kanaName: 'タンザン ココロ',
  },
  {
    characterId: 112,
    jaName: '飛鬼 仁',
    kanaName: 'ヒキ ジン',
  },
  {
    characterId: 113,
    jaName: '朝露 幻子',
    kanaName: 'アサツユ ゲンコ',
  },
  {
    characterId: 114,
    jaName: '弓月 ディアーナ',
    kanaName: 'ユミツキ ディアーナ',
  },
  {
    characterId: 115,
    jaName: '冬海 もふ',
    kanaName: 'フユミ モフ',
  },
  {
    characterId: 116,
    jaName: '氷哀 六花',
    kanaName: 'ヒアイ リッカ',
  },
];

export const CharacterData: CharacterData[] = [
  {
    characterId: 1,
    statusType: StatusType.Power,
    rarity: Rarity.Uncommon,
    fileName: 'f001',
    cardType: CartType.Battle,
  },
  {
    characterId: 1,
    statusType: StatusType.Power,
    rarity: Rarity.SuperRare,
    fileName: 'f002',
    cardType: CartType.Battle,
  },
  {
    characterId: 2,
    statusType: StatusType.Speeder,
    rarity: Rarity.Uncommon,
    fileName: 'f003',
    cardType: CartType.Battle,
  },
  {
    characterId: 2,
    statusType: StatusType.Magica,
    rarity: Rarity.SuperRare,
    fileName: 'f004',
    cardType: CartType.Battle,
  },
  {
    characterId: 3,
    statusType: StatusType.Power,
    rarity: Rarity.Uncommon,
    fileName: 'f007',
    cardType: CartType.Battle,
  },
  {
    characterId: 3,
    statusType: StatusType.Power,
    rarity: Rarity.SuperRare,
    fileName: 'f008',
    cardType: CartType.Battle,
  },
  {
    characterId: 3,
    statusType: StatusType.Magica,
    rarity: Rarity.UltraRare,
    fileName: 'f005',
    cardType: CartType.Battle,
  },
  {
    characterId: 3,
    statusType: StatusType.Power,
    rarity: Rarity.LegendRare,
    fileName: 'f006',
    cardType: CartType.Battle,
  },
  {
    characterId: 4,
    statusType: StatusType.Power,
    rarity: Rarity.Common,
    fileName: 'f009',
    cardType: CartType.Battle,
  },
  {
    characterId: 4,
    statusType: StatusType.Power,
    rarity: Rarity.Rare,
    fileName: 'f010',
    cardType: CartType.Battle,
  },
  {
    characterId: 5,
    statusType: StatusType.Magica,
    rarity: Rarity.Common,
    fileName: 'f011',
    cardType: CartType.Battle,
  },
  {
    characterId: 5,
    statusType: StatusType.Magica,
    rarity: Rarity.Rare,
    fileName: 'f012',
    cardType: CartType.Battle,
  },
  {
    characterId: 6,
    statusType: StatusType.Speeder,
    rarity: Rarity.SuperRare,
    fileName: 'f013',
    cardType: CartType.Battle,
  },
  {
    characterId: 6,
    statusType: StatusType.Magica,
    rarity: Rarity.UltraRare,
    fileName: 'f014',
    cardType: CartType.Battle,
  },
  {
    characterId: 7,
    statusType: StatusType.Magica,
    rarity: Rarity.Common,
    fileName: 'f015',
    cardType: CartType.Battle,
  },
  {
    characterId: 7,
    statusType: StatusType.Power,
    rarity: Rarity.Rare,
    fileName: 'f016',
    cardType: CartType.Battle,
  },
  {
    characterId: 8,
    statusType: StatusType.Speeder,
    rarity: Rarity.Common,
    fileName: 'f017',
    cardType: CartType.Battle,
  },
  {
    characterId: 8,
    statusType: StatusType.Speeder,
    rarity: Rarity.Rare,
    fileName: 'f018',
    cardType: CartType.Battle,
  },
  {
    characterId: 9,
    statusType: StatusType.Power,
    rarity: Rarity.Common,
    fileName: 'f019',
    cardType: CartType.Battle,
  },
  {
    characterId: 9,
    statusType: StatusType.Magica,
    rarity: Rarity.Rare,
    fileName: 'f020',
    cardType: CartType.Battle,
  },
  {
    characterId: 10,
    statusType: StatusType.Magica,
    rarity: Rarity.Common,
    fileName: 'f021',
    cardType: CartType.Battle,
  },
  {
    characterId: 10,
    statusType: StatusType.Magica,
    rarity: Rarity.Rare,
    fileName: 'f022',
    cardType: CartType.Battle,
  },
  {
    characterId: 11,
    statusType: StatusType.Balance,
    rarity: Rarity.SuperRare,
    fileName: 'f023',
    cardType: CartType.Battle,
  },
  {
    characterId: 11,
    statusType: StatusType.Balance,
    rarity: Rarity.UltraRare,
    fileName: 'f024',
    cardType: CartType.Battle,
  },
  {
    characterId: 11,
    statusType: StatusType.Balance,
    rarity: Rarity.Rare,
    fileName: 'f025',
    cardType: CartType.Support,
  },
  {
    characterId: 11,
    statusType: StatusType.Balance,
    rarity: Rarity.UltraRare,
    fileName: 'f026',
    cardType: CartType.Support,
  },
  {
    characterId: 12,
    statusType: StatusType.Magica,
    rarity: Rarity.Rare,
    fileName: 'f027',
    cardType: CartType.Battle,
  },
  {
    characterId: 12,
    statusType: StatusType.Magica,
    rarity: Rarity.SuperRare,
    fileName: 'f028',
    cardType: CartType.Battle,
  },
  {
    characterId: 13,
    statusType: StatusType.Magica,
    rarity: Rarity.Uncommon,
    fileName: 'f029',
    cardType: CartType.Battle,
  },
  {
    characterId: 13,
    statusType: StatusType.Magica,
    rarity: Rarity.Rare,
    fileName: 'f030',
    cardType: CartType.Battle,
  },
  {
    characterId: 13,
    statusType: StatusType.Speeder,
    rarity: Rarity.SuperRare,
    fileName: 'f031',
    cardType: CartType.Battle,
  },
  {
    characterId: 13,
    statusType: StatusType.Power,
    rarity: Rarity.UltraRare,
    fileName: 'f032',
    cardType: CartType.Battle,
  },
  {
    characterId: 13,
    statusType: StatusType.Magica,
    rarity: Rarity.SuperRare,
    fileName: 'f033',
    cardType: CartType.Battle,
  },
  {
    characterId: 13,
    statusType: StatusType.Magica,
    rarity: Rarity.UltraRare,
    fileName: 'f034',
    cardType: CartType.Battle,
  },
  {
    characterId: 14,
    statusType: StatusType.Magica,
    rarity: Rarity.Rare,
    fileName: 'f035',
    cardType: CartType.Battle,
  },
  {
    characterId: 14,
    statusType: StatusType.Power,
    rarity: Rarity.SuperRare,
    fileName: 'f036',
    cardType: CartType.Battle,
  },
  {
    characterId: 15,
    statusType: StatusType.Balance,
    rarity: Rarity.Common,
    fileName: 'f037',
    cardType: CartType.Battle,
  },
  {
    characterId: 15,
    statusType: StatusType.Magica,
    rarity: Rarity.UltraRare,
    fileName: 'f038',
    cardType: CartType.Battle,
  },
  {
    characterId: 16,
    statusType: StatusType.Speeder,
    rarity: Rarity.Common,
    fileName: 'f039',
    cardType: CartType.Support,
  },
  {
    characterId: 16,
    statusType: StatusType.Speeder,
    rarity: Rarity.Uncommon,
    fileName: 'f040',
    cardType: CartType.Support,
  },
  {
    characterId: 16,
    statusType: StatusType.Speeder,
    rarity: Rarity.Common,
    fileName: 'f041',
    cardType: CartType.Support,
  },
  {
    characterId: 16,
    statusType: StatusType.Speeder,
    rarity: Rarity.Uncommon,
    fileName: 'f042',
    cardType: CartType.Support,
  },
  {
    characterId: 17,
    statusType: StatusType.Magica,
    rarity: Rarity.Rare,
    fileName: 'f043',
    cardType: CartType.Battle,
  },
  {
    characterId: 17,
    statusType: StatusType.Magica,
    rarity: Rarity.Rare,
    fileName: 'f044',
    cardType: CartType.Battle,
  },
  {
    characterId: 17,
    statusType: StatusType.Magica,
    rarity: Rarity.Rare,
    fileName: 'f045',
    cardType: CartType.Battle,
  },
  {
    characterId: 17,
    statusType: StatusType.Magica,
    rarity: Rarity.Rare,
    fileName: 'f046',
    cardType: CartType.Battle,
  },
  {
    characterId: 17,
    statusType: StatusType.Magica,
    rarity: Rarity.Rare,
    fileName: 'f047',
    cardType: CartType.Battle,
  },
  {
    characterId: 16,
    statusType: StatusType.Balance,
    rarity: Rarity.SuperRare,
    fileName: 'f048',
    cardType: CartType.Support,
  },
  {
    characterId: 17,
    statusType: StatusType.Power,
    rarity: Rarity.UltraRare,
    fileName: 'f049',
    cardType: CartType.Battle,
  },
  {
    characterId: 18,
    statusType: StatusType.Balance,
    rarity: Rarity.Common,
    fileName: 'f050',
    cardType: CartType.Battle,
  },
  {
    characterId: 18,
    statusType: StatusType.Magica,
    rarity: Rarity.SuperRare,
    fileName: 'f051',
    cardType: CartType.Battle,
  },
  {
    characterId: 19,
    statusType: StatusType.Power,
    rarity: Rarity.SuperRare,
    fileName: 'f052',
    cardType: CartType.Battle,
  },
  {
    characterId: 19,
    statusType: StatusType.Magica,
    rarity: Rarity.UltraRare,
    fileName: 'f053',
    cardType: CartType.Battle,
  },
  {
    characterId: 20,
    statusType: StatusType.Balance,
    rarity: Rarity.Common,
    fileName: 'f054',
    cardType: CartType.Support,
  },
  {
    characterId: 20,
    statusType: StatusType.Balance,
    rarity: Rarity.Common,
    fileName: 'f055',
    cardType: CartType.Support,
  },
  {
    characterId: 20,
    statusType: StatusType.Balance,
    rarity: Rarity.Uncommon,
    fileName: 'f056',
    cardType: CartType.Support,
  },
  {
    characterId: 20,
    statusType: StatusType.Balance,
    rarity: Rarity.Uncommon,
    fileName: 'f057',
    cardType: CartType.Support,
  },
  {
    characterId: 20,
    statusType: StatusType.Magica,
    rarity: Rarity.Rare,
    fileName: 'f065',
    cardType: CartType.Battle,
  },
  {
    characterId: 20,
    statusType: StatusType.Magica,
    rarity: Rarity.SuperRare,
    fileName: 'f063',
    cardType: CartType.Support,
  },
  {
    characterId: 21,
    statusType: StatusType.Balance,
    rarity: Rarity.UltraRare,
    fileName: 'f058',
    cardType: CartType.Battle,
  },
  {
    characterId: 21,
    statusType: StatusType.Balance,
    rarity: Rarity.UltraRare,
    fileName: 'f059',
    cardType: CartType.Battle,
  },
  {
    characterId: 21,
    statusType: StatusType.Balance,
    rarity: Rarity.UltraRare,
    fileName: 'f060',
    cardType: CartType.Battle,
  },
  {
    characterId: 21,
    statusType: StatusType.Balance,
    rarity: Rarity.UltraRare,
    fileName: 'f061',
    cardType: CartType.Battle,
  },
  {
    characterId: 21,
    statusType: StatusType.Balance,
    rarity: Rarity.UltraRare,
    fileName: 'f062',
    cardType: CartType.Battle,
  },
  {
    characterId: 21,
    statusType: StatusType.Balance,
    rarity: Rarity.LegendRare,
    fileName: 'f064',
    cardType: CartType.Battle,
  },
  {
    characterId: 21,
    statusType: StatusType.Balance,
    rarity: Rarity.UltraRare,
    fileName: 'f066',
    cardType: CartType.Support,
  },
  {
    characterId: 22,
    statusType: StatusType.Balance,
    rarity: Rarity.SuperRare,
    fileName: 'f067',
    cardType: CartType.Battle,
  },
  {
    characterId: 22,
    statusType: StatusType.Balance,
    rarity: Rarity.UltraRare,
    fileName: 'f068',
    cardType: CartType.Battle,
  },
  {
    characterId: 23,
    statusType: StatusType.Balance,
    rarity: Rarity.Common,
    fileName: 'f069',
    cardType: CartType.Battle,
  },
  {
    characterId: 23,
    statusType: StatusType.Speeder,
    rarity: Rarity.Rare,
    fileName: 'f070',
    cardType: CartType.Battle,
  },
  {
    characterId: 24,
    statusType: StatusType.Balance,
    rarity: Rarity.Common,
    fileName: 'f071',
    cardType: CartType.Battle,
  },
  {
    characterId: 24,
    statusType: StatusType.Speeder,
    rarity: Rarity.Rare,
    fileName: 'f072',
    cardType: CartType.Battle,
  },
  {
    characterId: 24,
    statusType: StatusType.Balance,
    rarity: Rarity.SuperRare,
    fileName: 'f074',
    cardType: CartType.Battle,
  },
  {
    characterId: 24,
    statusType: StatusType.Balance,
    rarity: Rarity.Uncommon,
    fileName: 'f073',
    cardType: CartType.Support,
  },
  {
    characterId: 25,
    statusType: StatusType.Speeder,
    rarity: Rarity.Common,
    fileName: 'f075',
    cardType: CartType.Battle,
  },
  {
    characterId: 25,
    statusType: StatusType.Speeder,
    rarity: Rarity.Rare,
    fileName: 'f076',
    cardType: CartType.Battle,
  },
  {
    characterId: 26,
    statusType: StatusType.Balance,
    rarity: Rarity.Common,
    fileName: 'f077',
    cardType: CartType.Battle,
  },
  {
    characterId: 26,
    statusType: StatusType.Balance,
    rarity: Rarity.Rare,
    fileName: 'f078',
    cardType: CartType.Battle,
  },
  {
    characterId: 27,
    statusType: StatusType.Balance,
    rarity: Rarity.Common,
    fileName: 'f079',
    cardType: CartType.Battle,
  },
  {
    characterId: 27,
    statusType: StatusType.Speeder,
    rarity: Rarity.Rare,
    fileName: 'f080',
    cardType: CartType.Battle,
  },
  {
    characterId: 28,
    statusType: StatusType.Magica,
    rarity: Rarity.Common,
    fileName: 'f081',
    cardType: CartType.Battle,
  },
  {
    characterId: 28,
    statusType: StatusType.Magica,
    rarity: Rarity.Rare,
    fileName: 'f082',
    cardType: CartType.Battle,
  },
  {
    characterId: 29,
    statusType: StatusType.Balance,
    rarity: Rarity.Common,
    fileName: 'f083',
    cardType: CartType.Battle,
  },
  {
    characterId: 29,
    statusType: StatusType.Magica,
    rarity: Rarity.SuperRare,
    fileName: 'f084',
    cardType: CartType.Battle,
  },
  {
    characterId: 29,
    statusType: StatusType.Balance,
    rarity: Rarity.Uncommon,
    fileName: 'f085',
    cardType: CartType.Support,
  },
  {
    characterId: 29,
    statusType: StatusType.Power,
    rarity: Rarity.SuperRare,
    fileName: 'f086',
    cardType: CartType.Support,
  },
  {
    characterId: 30,
    statusType: StatusType.Magica,
    rarity: Rarity.SuperRare,
    fileName: 'f089',
    cardType: CartType.Battle,
  },
  {
    characterId: 30,
    statusType: StatusType.Speeder,
    rarity: Rarity.UltraRare,
    fileName: 'f088',
    cardType: CartType.Battle,
  },
  {
    characterId: 30,
    statusType: StatusType.Magica,
    rarity: Rarity.LegendRare,
    fileName: 'f090',
    cardType: CartType.Battle,
  },
  {
    characterId: 30,
    statusType: StatusType.Magica,
    rarity: Rarity.UltraRare,
    fileName: 'f087',
    cardType: CartType.Support,
  },
  {
    characterId: 31,
    statusType: StatusType.Balance,
    rarity: Rarity.Common,
    fileName: 'f091',
    cardType: CartType.Support,
  },
  {
    characterId: 31,
    statusType: StatusType.Power,
    rarity: Rarity.Uncommon,
    fileName: 'f093',
    cardType: CartType.Support,
  },
  {
    characterId: 31,
    statusType: StatusType.Magica,
    rarity: Rarity.Rare,
    fileName: 'f092',
    cardType: CartType.Support,
  },
  {
    characterId: 31,
    statusType: StatusType.Power,
    rarity: Rarity.SuperRare,
    fileName: 'f094',
    cardType: CartType.Support,
  },
  {
    characterId: 32,
    statusType: StatusType.Power,
    rarity: Rarity.Common,
    fileName: 'f095',
    cardType: CartType.Battle,
  },
  {
    characterId: 32,
    statusType: StatusType.Power,
    rarity: Rarity.UltraRare,
    fileName: 'f096',
    cardType: CartType.Battle,
  },
  {
    characterId: 33,
    statusType: StatusType.Magica,
    rarity: Rarity.Common,
    fileName: 'f097',
    cardType: CartType.Battle,
  },
  {
    characterId: 33,
    statusType: StatusType.Magica,
    rarity: Rarity.Rare,
    fileName: 'f098',
    cardType: CartType.Battle,
  },
  {
    characterId: 34,
    statusType: StatusType.Magica,
    rarity: Rarity.UltraRare,
    fileName: 'f099',
    cardType: CartType.Battle,
  },
  {
    characterId: 34,
    statusType: StatusType.Magica,
    rarity: Rarity.LegendRare,
    fileName: 'f100',
    cardType: CartType.Battle,
  },
  {
    characterId: 35,
    statusType: StatusType.Magica,
    rarity: Rarity.UltraRare,
    fileName: 'f101',
    cardType: CartType.Battle,
  },
  {
    characterId: 35,
    statusType: StatusType.Magica,
    rarity: Rarity.LegendRare,
    fileName: 'f102',
    cardType: CartType.Battle,
  },
  {
    characterId: 36,
    statusType: StatusType.Magica,
    rarity: Rarity.Rare,
    fileName: 'f103',
    cardType: CartType.Battle,
  },
  {
    characterId: 36,
    statusType: StatusType.Power,
    rarity: Rarity.SuperRare,
    fileName: 'f104',
    cardType: CartType.Battle,
  },
  {
    characterId: 36,
    statusType: StatusType.Magica,
    rarity: Rarity.UltraRare,
    fileName: 'f105',
    cardType: CartType.Battle,
  },
  {
    characterId: 37,
    statusType: StatusType.Speeder,
    rarity: Rarity.Common,
    fileName: 'f106',
    cardType: CartType.Battle,
  },
  {
    characterId: 37,
    statusType: StatusType.Speeder,
    rarity: Rarity.Rare,
    fileName: 'f107',
    cardType: CartType.Battle,
  },
  {
    characterId: 38,
    statusType: StatusType.Speeder,
    rarity: Rarity.Uncommon,
    fileName: 'f108',
    cardType: CartType.Battle,
  },
  {
    characterId: 38,
    statusType: StatusType.Speeder,
    rarity: Rarity.Rare,
    fileName: 'f109',
    cardType: CartType.Battle,
  },
  {
    characterId: 38,
    statusType: StatusType.Magica,
    rarity: Rarity.UltraRare,
    fileName: 'f111',
    cardType: CartType.Battle,
  },
  {
    characterId: 38,
    statusType: StatusType.Magica,
    rarity: Rarity.Rare,
    fileName: 'f110',
    cardType: CartType.Support,
  },
  {
    characterId: 39,
    statusType: StatusType.Balance,
    rarity: Rarity.Common,
    fileName: 'f112',
    cardType: CartType.Battle,
  },
  {
    characterId: 39,
    statusType: StatusType.Speeder,
    rarity: Rarity.SuperRare,
    fileName: 'f113',
    cardType: CartType.Battle,
  },
  {
    characterId: 39,
    statusType: StatusType.Speeder,
    rarity: Rarity.UltraRare,
    fileName: 'f115',
    cardType: CartType.Battle,
  },
  {
    characterId: 39,
    statusType: StatusType.Speeder,
    rarity: Rarity.Rare,
    fileName: 'f114',
    cardType: CartType.Support,
  },
  {
    characterId: 40,
    statusType: StatusType.Balance,
    rarity: Rarity.Common,
    fileName: 'f119',
    cardType: CartType.Battle,
  },
  {
    characterId: 40,
    statusType: StatusType.Power,
    rarity: Rarity.Rare,
    fileName: 'f120',
    cardType: CartType.Battle,
  },
  {
    characterId: 40,
    statusType: StatusType.Power,
    rarity: Rarity.SuperRare,
    fileName: 'f122',
    cardType: CartType.Battle,
  },
  {
    characterId: 40,
    statusType: StatusType.Power,
    rarity: Rarity.SuperRare,
    fileName: 'f121',
    cardType: CartType.Support,
  },
  {
    characterId: 41,
    statusType: StatusType.Magica,
    rarity: Rarity.Common,
    fileName: 'f123',
    cardType: CartType.Battle,
  },
  {
    characterId: 41,
    statusType: StatusType.Magica,
    rarity: Rarity.Rare,
    fileName: 'f124',
    cardType: CartType.Battle,
  },
  {
    characterId: 42,
    statusType: StatusType.Speeder,
    rarity: Rarity.Rare,
    fileName: 'f125',
    cardType: CartType.Battle,
  },
  {
    characterId: 42,
    statusType: StatusType.Speeder,
    rarity: Rarity.UltraRare,
    fileName: 'f126',
    cardType: CartType.Battle,
  },
  {
    characterId: 43,
    statusType: StatusType.Balance,
    rarity: Rarity.Common,
    fileName: 'f127',
    cardType: CartType.Support,
  },
  {
    characterId: 43,
    statusType: StatusType.Balance,
    rarity: Rarity.Rare,
    fileName: 'f128',
    cardType: CartType.Support,
  },
  {
    characterId: 43,
    statusType: StatusType.Magica,
    rarity: Rarity.SuperRare,
    fileName: 'f129',
    cardType: CartType.Support,
  },
  {
    characterId: 43,
    statusType: StatusType.Magica,
    rarity: Rarity.UltraRare,
    fileName: 'f130',
    cardType: CartType.Support,
  },
  {
    characterId: 44,
    statusType: StatusType.Balance,
    rarity: Rarity.Common,
    fileName: 'f131',
    cardType: CartType.Battle,
  },
  {
    characterId: 44,
    statusType: StatusType.Power,
    rarity: Rarity.Rare,
    fileName: 'f132',
    cardType: CartType.Battle,
  },
  {
    characterId: 45,
    statusType: StatusType.Power,
    rarity: Rarity.Uncommon,
    fileName: 'f133',
    cardType: CartType.Battle,
  },
  {
    characterId: 45,
    statusType: StatusType.Power,
    rarity: Rarity.Rare,
    fileName: 'f134',
    cardType: CartType.Battle,
  },
  {
    characterId: 46,
    statusType: StatusType.Power,
    rarity: Rarity.Common,
    fileName: 'f135',
    cardType: CartType.Battle,
  },
  {
    characterId: 46,
    statusType: StatusType.Power,
    rarity: Rarity.SuperRare,
    fileName: 'f136',
    cardType: CartType.Battle,
  },
  {
    characterId: 47,
    statusType: StatusType.Balance,
    rarity: Rarity.Common,
    fileName: 'f137',
    cardType: CartType.Battle,
  },
  {
    characterId: 47,
    statusType: StatusType.Balance,
    rarity: Rarity.SuperRare,
    fileName: 'f138',
    cardType: CartType.Battle,
  },
  {
    characterId: 47,
    statusType: StatusType.Balance,
    rarity: Rarity.UltraRare,
    fileName: 'f140',
    cardType: CartType.Battle,
  },
  {
    characterId: 47,
    statusType: StatusType.Balance,
    rarity: Rarity.Rare,
    fileName: 'f139',
    cardType: CartType.Support,
  },
  {
    characterId: 48,
    statusType: StatusType.Magica,
    rarity: Rarity.Common,
    fileName: 'f141',
    cardType: CartType.Battle,
  },
  {
    characterId: 48,
    statusType: StatusType.Magica,
    rarity: Rarity.Rare,
    fileName: 'f142',
    cardType: CartType.Battle,
  },
  {
    characterId: 48,
    statusType: StatusType.Magica,
    rarity: Rarity.SuperRare,
    fileName: 'f143',
    cardType: CartType.Battle,
  },
  {
    characterId: 48,
    statusType: StatusType.Magica,
    rarity: Rarity.UltraRare,
    fileName: 'f144',
    cardType: CartType.Battle,
  },
  {
    characterId: 49,
    statusType: StatusType.Magica,
    rarity: Rarity.Common,
    fileName: 'f145',
    cardType: CartType.Battle,
  },
  {
    characterId: 49,
    statusType: StatusType.Power,
    rarity: Rarity.Rare,
    fileName: 'f146',
    cardType: CartType.Battle,
  },
  {
    characterId: 50,
    statusType: StatusType.Balance,
    rarity: Rarity.Common,
    fileName: 'f147',
    cardType: CartType.Battle,
  },
  {
    characterId: 50,
    statusType: StatusType.Balance,
    rarity: Rarity.Rare,
    fileName: 'f148',
    cardType: CartType.Battle,
  },
  {
    characterId: 51,
    statusType: StatusType.Balance,
    rarity: Rarity.Uncommon,
    fileName: 'f149',
    cardType: CartType.Battle,
  },
  {
    characterId: 51,
    statusType: StatusType.Magica,
    rarity: Rarity.Rare,
    fileName: 'f150',
    cardType: CartType.Battle,
  },
  {
    characterId: 51,
    statusType: StatusType.Magica,
    rarity: Rarity.SuperRare,
    fileName: 'f152',
    cardType: CartType.Battle,
  },
  {
    characterId: 51,
    statusType: StatusType.Power,
    rarity: Rarity.Rare,
    fileName: 'f151',
    cardType: CartType.Support,
  },
  {
    characterId: 52,
    statusType: StatusType.Speeder,
    rarity: Rarity.Common,
    fileName: 'f153',
    cardType: CartType.Battle,
  },
  {
    characterId: 52,
    statusType: StatusType.Speeder,
    rarity: Rarity.Rare,
    fileName: 'f154',
    cardType: CartType.Battle,
  },
  {
    characterId: 53,
    statusType: StatusType.Speeder,
    rarity: Rarity.Common,
    fileName: 'f155',
    cardType: CartType.Battle,
  },
  {
    characterId: 53,
    statusType: StatusType.Speeder,
    rarity: Rarity.SuperRare,
    fileName: 'f156',
    cardType: CartType.Battle,
  },
  {
    characterId: 54,
    statusType: StatusType.Magica,
    rarity: Rarity.Common,
    fileName: 'f157',
    cardType: CartType.Battle,
  },
  {
    characterId: 54,
    statusType: StatusType.Magica,
    rarity: Rarity.Rare,
    fileName: 'f158',
    cardType: CartType.Battle,
  },
  {
    characterId: 55,
    statusType: StatusType.Balance,
    rarity: Rarity.Common,
    fileName: 'f159',
    cardType: CartType.Battle,
  },
  {
    characterId: 55,
    statusType: StatusType.Speeder,
    rarity: Rarity.Rare,
    fileName: 'f160',
    cardType: CartType.Battle,
  },
  {
    characterId: 55,
    statusType: StatusType.Speeder,
    rarity: Rarity.SuperRare,
    fileName: 'f162',
    cardType: CartType.Battle,
  },
  {
    characterId: 55,
    statusType: StatusType.Speeder,
    rarity: Rarity.Uncommon,
    fileName: 'f161',
    cardType: CartType.Support,
  },
  {
    characterId: 56,
    statusType: StatusType.Balance,
    rarity: Rarity.Common,
    fileName: 'f163',
    cardType: CartType.Battle,
  },
  {
    characterId: 56,
    statusType: StatusType.Power,
    rarity: Rarity.Rare,
    fileName: 'f164',
    cardType: CartType.Battle,
  },
  {
    characterId: 57,
    statusType: StatusType.Power,
    rarity: Rarity.Common,
    fileName: 'f165',
    cardType: CartType.Battle,
  },
  {
    characterId: 57,
    statusType: StatusType.Power,
    rarity: Rarity.Rare,
    fileName: 'f166',
    cardType: CartType.Battle,
  },
  {
    characterId: 58,
    statusType: StatusType.Magica,
    rarity: Rarity.Common,
    fileName: 'f167',
    cardType: CartType.Battle,
  },
  {
    characterId: 58,
    statusType: StatusType.Magica,
    rarity: Rarity.Rare,
    fileName: 'f168',
    cardType: CartType.Battle,
  },
  {
    characterId: 59,
    statusType: StatusType.Speeder,
    rarity: Rarity.Uncommon,
    fileName: 'f169',
    cardType: CartType.Battle,
  },
  {
    characterId: 59,
    statusType: StatusType.Magica,
    rarity: Rarity.SuperRare,
    fileName: 'f170',
    cardType: CartType.Battle,
  },
  {
    characterId: 59,
    statusType: StatusType.Magica,
    rarity: Rarity.Rare,
    fileName: 'f171',
    cardType: CartType.Battle,
  },
  {
    characterId: 59,
    statusType: StatusType.Magica,
    rarity: Rarity.UltraRare,
    fileName: 'f172',
    cardType: CartType.Battle,
  },
  {
    characterId: 59,
    statusType: StatusType.Magica,
    rarity: Rarity.LegendRare,
    fileName: 'f174',
    cardType: CartType.Battle,
  },
  {
    characterId: 59,
    statusType: StatusType.Magica,
    rarity: Rarity.SuperRare,
    fileName: 'f173',
    cardType: CartType.Support,
  },
  {
    characterId: 60,
    statusType: StatusType.Magica,
    rarity: Rarity.Common,
    fileName: 'f175',
    cardType: CartType.Battle,
  },
  {
    characterId: 60,
    statusType: StatusType.Magica,
    rarity: Rarity.Uncommon,
    fileName: 'f177',
    cardType: CartType.Battle,
  },
  {
    characterId: 60,
    statusType: StatusType.Magica,
    rarity: Rarity.SuperRare,
    fileName: 'f176',
    cardType: CartType.Battle,
  },
  {
    characterId: 60,
    statusType: StatusType.Magica,
    rarity: Rarity.UltraRare,
    fileName: 'f178',
    cardType: CartType.Battle,
  },
  {
    characterId: 61,
    statusType: StatusType.Speeder,
    rarity: Rarity.Common,
    fileName: 'f179',
    cardType: CartType.Battle,
  },
  {
    characterId: 61,
    statusType: StatusType.Speeder,
    rarity: Rarity.SuperRare,
    fileName: 'f180',
    cardType: CartType.Battle,
  },
  {
    characterId: 62,
    statusType: StatusType.God,
    rarity: Rarity.LegendRare,
    fileName: 'f208',
    cardType: CartType.Battle,
  },
  {
    characterId: 63,
    statusType: StatusType.Balance,
    rarity: Rarity.Common,
    fileName: 'f209',
    cardType: CartType.Battle,
  },
  {
    characterId: 63,
    statusType: StatusType.Speeder,
    rarity: Rarity.SuperRare,
    fileName: 'f210',
    cardType: CartType.Battle,
  },
  {
    characterId: 63,
    statusType: StatusType.Power,
    rarity: Rarity.UltraRare,
    fileName: 'f212',
    cardType: CartType.Battle,
  },
  {
    characterId: 63,
    statusType: StatusType.Balance,
    rarity: Rarity.SuperRare,
    fileName: 'f211',
    cardType: CartType.Support,
  },
  {
    characterId: 64,
    statusType: StatusType.Magica,
    rarity: Rarity.Common,
    fileName: 'f213',
    cardType: CartType.Battle,
  },
  {
    characterId: 64,
    statusType: StatusType.Magica,
    rarity: Rarity.Rare,
    fileName: 'f214',
    cardType: CartType.Battle,
  },
  {
    characterId: 65,
    statusType: StatusType.Balance,
    rarity: Rarity.Common,
    fileName: 'f215',
    cardType: CartType.Battle,
  },
  {
    characterId: 65,
    statusType: StatusType.Balance,
    rarity: Rarity.SuperRare,
    fileName: 'f216',
    cardType: CartType.Battle,
  },
  {
    characterId: 65,
    statusType: StatusType.Balance,
    rarity: Rarity.UltraRare,
    fileName: 'f218',
    cardType: CartType.Battle,
  },
  {
    characterId: 65,
    statusType: StatusType.Balance,
    rarity: Rarity.Uncommon,
    fileName: 'f217',
    cardType: CartType.Support,
  },
  {
    characterId: 66,
    statusType: StatusType.Magica,
    rarity: Rarity.Common,
    fileName: 'f219',
    cardType: CartType.Battle,
  },
  {
    characterId: 66,
    statusType: StatusType.Magica,
    rarity: Rarity.Rare,
    fileName: 'f220',
    cardType: CartType.Battle,
  },
  {
    characterId: 66,
    statusType: StatusType.Magica,
    rarity: Rarity.SuperRare,
    fileName: 'f221',
    cardType: CartType.Battle,
  },
  {
    characterId: 66,
    statusType: StatusType.Magica,
    rarity: Rarity.UltraRare,
    fileName: 'f222',
    cardType: CartType.Battle,
  },
  {
    characterId: 67,
    statusType: StatusType.Power,
    rarity: Rarity.Common,
    fileName: 'f223',
    cardType: CartType.Battle,
  },
  {
    characterId: 67,
    statusType: StatusType.Magica,
    rarity: Rarity.SuperRare,
    fileName: 'f224',
    cardType: CartType.Battle,
  },
  {
    characterId: 68,
    statusType: StatusType.Balance,
    rarity: Rarity.Common,
    fileName: 'f225',
    cardType: CartType.Battle,
  },
  {
    characterId: 68,
    statusType: StatusType.Balance,
    rarity: Rarity.Rare,
    fileName: 'f226',
    cardType: CartType.Battle,
  },
  {
    characterId: 68,
    statusType: StatusType.Balance,
    rarity: Rarity.SuperRare,
    fileName: 'f228',
    cardType: CartType.Battle,
  },
  {
    characterId: 68,
    statusType: StatusType.Balance,
    rarity: Rarity.SuperRare,
    fileName: 'f227',
    cardType: CartType.Support,
  },
  {
    characterId: 69,
    statusType: StatusType.Speeder,
    rarity: Rarity.Common,
    fileName: 'f229',
    cardType: CartType.Support,
  },
  {
    characterId: 69,
    statusType: StatusType.Speeder,
    rarity: Rarity.Uncommon,
    fileName: 'f230',
    cardType: CartType.Support,
  },
  {
    characterId: 69,
    statusType: StatusType.Speeder,
    rarity: Rarity.Rare,
    fileName: 'f231',
    cardType: CartType.Support,
  },
  {
    characterId: 69,
    statusType: StatusType.Speeder,
    rarity: Rarity.SuperRare,
    fileName: 'f232',
    cardType: CartType.Support,
  },
  {
    characterId: 70,
    statusType: StatusType.Speeder,
    rarity: Rarity.Common,
    fileName: 'f233',
    cardType: CartType.Battle,
  },
  {
    characterId: 70,
    statusType: StatusType.Magica,
    rarity: Rarity.SuperRare,
    fileName: 'f234',
    cardType: CartType.Battle,
  },
  {
    characterId: 71,
    statusType: StatusType.Magica,
    rarity: Rarity.Common,
    fileName: 'f235',
    cardType: CartType.Battle,
  },
  {
    characterId: 71,
    statusType: StatusType.Magica,
    rarity: Rarity.Rare,
    fileName: 'f236',
    cardType: CartType.Battle,
  },
  {
    characterId: 72,
    statusType: StatusType.Speeder,
    rarity: Rarity.Common,
    fileName: 'f237',
    cardType: CartType.Battle,
  },
  {
    characterId: 72,
    statusType: StatusType.Speeder,
    rarity: Rarity.Rare,
    fileName: 'f238',
    cardType: CartType.Battle,
  },
  {
    characterId: 74,
    statusType: StatusType.Power,
    rarity: Rarity.Common,
    fileName: 'f239',
    cardType: CartType.Battle,
  },
  {
    characterId: 74,
    statusType: StatusType.Magica,
    rarity: Rarity.Rare,
    fileName: 'f240',
    cardType: CartType.Battle,
  },
  {
    characterId: 75,
    statusType: StatusType.Balance,
    rarity: Rarity.Common,
    fileName: 'f241',
    cardType: CartType.Battle,
  },
  {
    characterId: 75,
    statusType: StatusType.Speeder,
    rarity: Rarity.Rare,
    fileName: 'f242',
    cardType: CartType.Battle,
  },
  {
    characterId: 76,
    statusType: StatusType.Balance,
    rarity: Rarity.Common,
    fileName: 'f243',
    cardType: CartType.Battle,
  },
  {
    characterId: 76,
    statusType: StatusType.Speeder,
    rarity: Rarity.Rare,
    fileName: 'f244',
    cardType: CartType.Battle,
  },
  {
    characterId: 76,
    statusType: StatusType.Magica,
    rarity: Rarity.SuperRare,
    fileName: 'f246',
    cardType: CartType.Battle,
  },
  {
    characterId: 76,
    statusType: StatusType.Balance,
    rarity: Rarity.SuperRare,
    fileName: 'f245',
    cardType: CartType.Support,
  },
  {
    characterId: 77,
    statusType: StatusType.Speeder,
    rarity: Rarity.Common,
    fileName: 'f247',
    cardType: CartType.Battle,
  },
  {
    characterId: 77,
    statusType: StatusType.Speeder,
    rarity: Rarity.SuperRare,
    fileName: 'f248',
    cardType: CartType.Battle,
  },
  {
    characterId: 78,
    statusType: StatusType.Balance,
    rarity: Rarity.Common,
    fileName: 'f249',
    cardType: CartType.Battle,
  },
  {
    characterId: 78,
    statusType: StatusType.Speeder,
    rarity: Rarity.Rare,
    fileName: 'f250',
    cardType: CartType.Battle,
  },
  {
    characterId: 79,
    statusType: StatusType.Speeder,
    rarity: Rarity.Rare,
    fileName: 'f252',
    cardType: CartType.Battle,
  },
  {
    characterId: 79,
    statusType: StatusType.Speeder,
    rarity: Rarity.SuperRare,
    fileName: 'f251',
    cardType: CartType.Battle,
  },
  {
    characterId: 80,
    statusType: StatusType.Magica,
    rarity: Rarity.Uncommon,
    fileName: 'f253',
    cardType: CartType.Battle,
  },
  {
    characterId: 80,
    statusType: StatusType.Magica,
    rarity: Rarity.Rare,
    fileName: 'f254',
    cardType: CartType.Battle,
  },
  {
    characterId: 81,
    statusType: StatusType.Balance,
    rarity: Rarity.Common,
    fileName: 'f255',
    cardType: CartType.Battle,
  },
  {
    characterId: 81,
    statusType: StatusType.Balance,
    rarity: Rarity.Rare,
    fileName: 'f256',
    cardType: CartType.Battle,
  },
  {
    characterId: 82,
    statusType: StatusType.Power,
    rarity: Rarity.Common,
    fileName: 'f257',
    cardType: CartType.Battle,
  },
  {
    characterId: 82,
    statusType: StatusType.Power,
    rarity: Rarity.Rare,
    fileName: 'f258',
    cardType: CartType.Battle,
  },
  {
    characterId: 83,
    statusType: StatusType.Power,
    rarity: Rarity.Common,
    fileName: 'f259',
    cardType: CartType.Battle,
  },
  {
    characterId: 83,
    statusType: StatusType.Power,
    rarity: Rarity.Rare,
    fileName: 'f260',
    cardType: CartType.Battle,
  },
  {
    characterId: 84,
    statusType: StatusType.Magica,
    rarity: Rarity.Rare,
    fileName: 'f261',
    cardType: CartType.Battle,
  },
  {
    characterId: 84,
    statusType: StatusType.Magica,
    rarity: Rarity.SuperRare,
    fileName: 'f262',
    cardType: CartType.Battle,
  },
  {
    characterId: 85,
    statusType: StatusType.Magica,
    rarity: Rarity.Uncommon,
    fileName: 'f263',
    cardType: CartType.Battle,
  },
  {
    characterId: 85,
    statusType: StatusType.Magica,
    rarity: Rarity.SuperRare,
    fileName: 'f264',
    cardType: CartType.Battle,
  },
  {
    characterId: 86,
    statusType: StatusType.Magica,
    rarity: Rarity.Common,
    fileName: 'f265',
    cardType: CartType.Battle,
  },
  {
    characterId: 86,
    statusType: StatusType.Magica,
    rarity: Rarity.Rare,
    fileName: 'f266',
    cardType: CartType.Battle,
  },
  {
    characterId: 86,
    statusType: StatusType.Magica,
    rarity: Rarity.UltraRare,
    fileName: 'f268',
    cardType: CartType.Battle,
  },
  {
    characterId: 86,
    statusType: StatusType.Magica,
    rarity: Rarity.Common,
    fileName: 'f267',
    cardType: CartType.Support,
  },
  {
    characterId: 87,
    statusType: StatusType.Magica,
    rarity: Rarity.Common,
    fileName: 'f278',
    cardType: CartType.Battle,
  },
  {
    characterId: 87,
    statusType: StatusType.Magica,
    rarity: Rarity.UltraRare,
    fileName: 'f279',
    cardType: CartType.Battle,
  },
  {
    characterId: 88,
    statusType: StatusType.Speeder,
    rarity: Rarity.Rare,
    fileName: 'f280',
    cardType: CartType.Battle,
  },
  {
    characterId: 88,
    statusType: StatusType.Magica,
    rarity: Rarity.UltraRare,
    fileName: 'f281',
    cardType: CartType.Battle,
  },
  {
    characterId: 88,
    statusType: StatusType.God,
    rarity: Rarity.LegendRare,
    fileName: 'f283',
    cardType: CartType.Battle,
  },
  {
    characterId: 88,
    statusType: StatusType.Balance,
    rarity: Rarity.Rare,
    fileName: 'f282',
    cardType: CartType.Support,
  },
  {
    characterId: 89,
    statusType: StatusType.Magica,
    rarity: Rarity.Common,
    fileName: 'f284',
    cardType: CartType.Battle,
  },
  {
    characterId: 89,
    statusType: StatusType.Magica,
    rarity: Rarity.Rare,
    fileName: 'f285',
    cardType: CartType.Battle,
  },
  {
    characterId: 90,
    statusType: StatusType.Balance,
    rarity: Rarity.Common,
    fileName: 'f286',
    cardType: CartType.Battle,
  },
  {
    characterId: 90,
    statusType: StatusType.Balance,
    rarity: Rarity.Rare,
    fileName: 'f287',
    cardType: CartType.Battle,
  },
  {
    characterId: 90,
    statusType: StatusType.Power,
    rarity: Rarity.Uncommon,
    fileName: 'f288',
    cardType: CartType.Support,
  },
  {
    characterId: 90,
    statusType: StatusType.Power,
    rarity: Rarity.SuperRare,
    fileName: 'f289',
    cardType: CartType.Support,
  },
  {
    characterId: 91,
    statusType: StatusType.Power,
    rarity: Rarity.Common,
    fileName: 'f290',
    cardType: CartType.Battle,
  },
  {
    characterId: 91,
    statusType: StatusType.Power,
    rarity: Rarity.Rare,
    fileName: 'f291',
    cardType: CartType.Battle,
  },
  {
    characterId: 92,
    statusType: StatusType.Power,
    rarity: Rarity.Common,
    fileName: 'f292',
    cardType: CartType.Battle,
  },
  {
    characterId: 92,
    statusType: StatusType.Power,
    rarity: Rarity.Rare,
    fileName: 'f293',
    cardType: CartType.Battle,
  },
  {
    characterId: 92,
    statusType: StatusType.Magica,
    rarity: Rarity.SuperRare,
    fileName: 'f295',
    cardType: CartType.Battle,
  },
  {
    characterId: 92,
    statusType: StatusType.Balance,
    rarity: Rarity.Uncommon,
    fileName: 'f294',
    cardType: CartType.Support,
  },
  {
    characterId: 93,
    statusType: StatusType.Magica,
    rarity: Rarity.Common,
    fileName: 'f296',
    cardType: CartType.Battle,
  },
  {
    characterId: 93,
    statusType: StatusType.Magica,
    rarity: Rarity.SuperRare,
    fileName: 'f297',
    cardType: CartType.Battle,
  },
  {
    characterId: 93,
    statusType: StatusType.Magica,
    rarity: Rarity.Uncommon,
    fileName: 'f298',
    cardType: CartType.Battle,
  },
  {
    characterId: 93,
    statusType: StatusType.Magica,
    rarity: Rarity.SuperRare,
    fileName: 'f299',
    cardType: CartType.Battle,
  },
  {
    characterId: 93,
    statusType: StatusType.Magica,
    rarity: Rarity.UltraRare,
    fileName: 'f300',
    cardType: CartType.Battle,
  },
  {
    characterId: 93,
    statusType: StatusType.Magica,
    rarity: Rarity.LegendRare,
    fileName: 'f301',
    cardType: CartType.Battle,
  },
  {
    characterId: 94,
    statusType: StatusType.Speeder,
    rarity: Rarity.Common,
    fileName: 'f302',
    cardType: CartType.Battle,
  },
  {
    characterId: 94,
    statusType: StatusType.Speeder,
    rarity: Rarity.Rare,
    fileName: 'f303',
    cardType: CartType.Battle,
  },
  {
    characterId: 95,
    statusType: StatusType.Balance,
    rarity: Rarity.Common,
    fileName: 'f304',
    cardType: CartType.Support,
  },
  {
    characterId: 95,
    statusType: StatusType.Magica,
    rarity: Rarity.Rare,
    fileName: 'f305',
    cardType: CartType.Support,
  },
  {
    characterId: 96,
    statusType: StatusType.Power,
    rarity: Rarity.Common,
    fileName: 'f306',
    cardType: CartType.Battle,
  },
  {
    characterId: 96,
    statusType: StatusType.Power,
    rarity: Rarity.Rare,
    fileName: 'f307',
    cardType: CartType.Battle,
  },
  {
    characterId: 96,
    statusType: StatusType.Power,
    rarity: Rarity.SuperRare,
    fileName: 'f309',
    cardType: CartType.Battle,
  },
  {
    characterId: 96,
    statusType: StatusType.Power,
    rarity: Rarity.UltraRare,
    fileName: 'f311',
    cardType: CartType.Battle,
  },
  {
    characterId: 96,
    statusType: StatusType.Power,
    rarity: Rarity.Rare,
    fileName: 'f308',
    cardType: CartType.Support,
  },
  {
    characterId: 96,
    statusType: StatusType.Power,
    rarity: Rarity.UltraRare,
    fileName: 'f310',
    cardType: CartType.Support,
  },
  {
    characterId: 97,
    statusType: StatusType.Balance,
    rarity: Rarity.Common,
    fileName: 'f312',
    cardType: CartType.Battle,
  },
  {
    characterId: 97,
    statusType: StatusType.Speeder,
    rarity: Rarity.SuperRare,
    fileName: 'f313',
    cardType: CartType.Battle,
  },
  {
    characterId: 97,
    statusType: StatusType.Speeder,
    rarity: Rarity.UltraRare,
    fileName: 'f315',
    cardType: CartType.Battle,
  },
  {
    characterId: 97,
    statusType: StatusType.Speeder,
    rarity: Rarity.Rare,
    fileName: 'f314',
    cardType: CartType.Support,
  },
  {
    characterId: 98,
    statusType: StatusType.Balance,
    rarity: Rarity.Common,
    fileName: 'f316',
    cardType: CartType.Battle,
  },
  {
    characterId: 98,
    statusType: StatusType.Power,
    rarity: Rarity.Rare,
    fileName: 'f317',
    cardType: CartType.Battle,
  },
  {
    characterId: 99,
    statusType: StatusType.Magica,
    rarity: Rarity.Uncommon,
    fileName: 'f318',
    cardType: CartType.Battle,
  },
  {
    characterId: 99,
    statusType: StatusType.Magica,
    rarity: Rarity.SuperRare,
    fileName: 'f319',
    cardType: CartType.Battle,
  },
  {
    characterId: 100,
    statusType: StatusType.Balance,
    rarity: Rarity.Common,
    fileName: 'f320',
    cardType: CartType.Battle,
  },
  {
    characterId: 100,
    statusType: StatusType.Magica,
    rarity: Rarity.Rare,
    fileName: 'f321',
    cardType: CartType.Battle,
  },
  {
    characterId: 101,
    statusType: StatusType.Magica,
    rarity: Rarity.Common,
    fileName: 'f322',
    cardType: CartType.Battle,
  },
  {
    characterId: 101,
    statusType: StatusType.Magica,
    rarity: Rarity.Rare,
    fileName: 'f323',
    cardType: CartType.Battle,
  },
  {
    characterId: 102,
    statusType: StatusType.Speeder,
    rarity: Rarity.Common,
    fileName: 'f324',
    cardType: CartType.Battle,
  },
  {
    characterId: 102,
    statusType: StatusType.Speeder,
    rarity: Rarity.Rare,
    fileName: 'f325',
    cardType: CartType.Battle,
  },
  {
    characterId: 103,
    statusType: StatusType.Magica,
    rarity: Rarity.Common,
    fileName: 'f326',
    cardType: CartType.Battle,
  },
  {
    characterId: 103,
    statusType: StatusType.Magica,
    rarity: Rarity.Rare,
    fileName: 'f327',
    cardType: CartType.Battle,
  },
  {
    characterId: 104,
    statusType: StatusType.Speeder,
    rarity: Rarity.Uncommon,
    fileName: 'f328',
    cardType: CartType.Battle,
  },
  {
    characterId: 104,
    statusType: StatusType.Magica,
    rarity: Rarity.SuperRare,
    fileName: 'f329',
    cardType: CartType.Battle,
  },
  {
    characterId: 104,
    statusType: StatusType.Magica,
    rarity: Rarity.UltraRare,
    fileName: 'f331',
    cardType: CartType.Battle,
  },
  {
    characterId: 104,
    statusType: StatusType.Magica,
    rarity: Rarity.Rare,
    fileName: 'f330',
    cardType: CartType.Support,
  },
  {
    characterId: 105,
    statusType: StatusType.Magica,
    rarity: Rarity.Rare,
    fileName: 'f332',
    cardType: CartType.Battle,
  },
  {
    characterId: 105,
    statusType: StatusType.Magica,
    rarity: Rarity.SuperRare,
    fileName: 'f333',
    cardType: CartType.Battle,
  },
  {
    characterId: 105,
    statusType: StatusType.Magica,
    rarity: Rarity.UltraRare,
    fileName: 'f335',
    cardType: CartType.Battle,
  },
  {
    characterId: 105,
    statusType: StatusType.Magica,
    rarity: Rarity.SuperRare,
    fileName: 'f334',
    cardType: CartType.Battle,
  },
  {
    characterId: 106,
    statusType: StatusType.Magica,
    rarity: Rarity.Common,
    fileName: 'f336',
    cardType: CartType.Battle,
  },
  {
    characterId: 106,
    statusType: StatusType.Magica,
    rarity: Rarity.Rare,
    fileName: 'f337',
    cardType: CartType.Battle,
  },
  {
    characterId: 107,
    statusType: StatusType.Speeder,
    rarity: Rarity.Common,
    fileName: 'f338',
    cardType: CartType.Battle,
  },
  {
    characterId: 107,
    statusType: StatusType.Speeder,
    rarity: Rarity.Rare,
    fileName: 'f339',
    cardType: CartType.Battle,
  },
  {
    characterId: 108,
    statusType: StatusType.Power,
    rarity: Rarity.Common,
    fileName: 'f340',
    cardType: CartType.Battle,
  },
  {
    characterId: 108,
    statusType: StatusType.Power,
    rarity: Rarity.SuperRare,
    fileName: 'f341',
    cardType: CartType.Battle,
  },
  {
    characterId: 109,
    statusType: StatusType.Speeder,
    rarity: Rarity.Uncommon,
    fileName: 'f342',
    cardType: CartType.Battle,
  },
  {
    characterId: 109,
    statusType: StatusType.Speeder,
    rarity: Rarity.SuperRare,
    fileName: 'f343',
    cardType: CartType.Battle,
  },
  {
    characterId: 110,
    statusType: StatusType.Magica,
    rarity: Rarity.Common,
    fileName: 'f344',
    cardType: CartType.Battle,
  },
  {
    characterId: 110,
    statusType: StatusType.Magica,
    rarity: Rarity.SuperRare,
    fileName: 'f345',
    cardType: CartType.Battle,
  },
  {
    characterId: 110,
    statusType: StatusType.Magica,
    rarity: Rarity.UltraRare,
    fileName: 'f347',
    cardType: CartType.Battle,
  },
  {
    characterId: 110,
    statusType: StatusType.Magica,
    rarity: Rarity.Uncommon,
    fileName: 'f346',
    cardType: CartType.Support,
  },
  {
    characterId: 111,
    statusType: StatusType.Speeder,
    rarity: Rarity.Common,
    fileName: 'f348',
    cardType: CartType.Battle,
  },
  {
    characterId: 111,
    statusType: StatusType.Speeder,
    rarity: Rarity.Rare,
    fileName: 'f349',
    cardType: CartType.Battle,
  },
  {
    characterId: 112,
    statusType: StatusType.Power,
    rarity: Rarity.Uncommon,
    fileName: 'f350',
    cardType: CartType.Battle,
  },
  {
    characterId: 112,
    statusType: StatusType.Power,
    rarity: Rarity.Rare,
    fileName: 'f351',
    cardType: CartType.Battle,
  },
  {
    characterId: 113,
    statusType: StatusType.Magica,
    rarity: Rarity.Rare,
    fileName: 'f352',
    cardType: CartType.Battle,
  },
  {
    characterId: 113,
    statusType: StatusType.Magica,
    rarity: Rarity.SuperRare,
    fileName: 'f353',
    cardType: CartType.Battle,
  },
  {
    characterId: 114,
    statusType: StatusType.Balance,
    rarity: Rarity.Rare,
    fileName: 'f354',
    cardType: CartType.Battle,
  },
  {
    characterId: 114,
    statusType: StatusType.Power,
    rarity: Rarity.Rare,
    fileName: 'f355',
    cardType: CartType.Battle,
  },
  {
    characterId: 114,
    statusType: StatusType.Speeder,
    rarity: Rarity.Rare,
    fileName: 'f356',
    cardType: CartType.Battle,
  },
  {
    characterId: 114,
    statusType: StatusType.Magica,
    rarity: Rarity.Rare,
    fileName: 'f357',
    cardType: CartType.Battle,
  },
  {
    characterId: 114,
    statusType: StatusType.Balance,
    rarity: Rarity.SuperRare,
    fileName: 'f358',
    cardType: CartType.Battle,
  },
  {
    characterId: 114,
    statusType: StatusType.Power,
    rarity: Rarity.SuperRare,
    fileName: 'f359',
    cardType: CartType.Battle,
  },
  {
    characterId: 114,
    statusType: StatusType.Speeder,
    rarity: Rarity.SuperRare,
    fileName: 'f360',
    cardType: CartType.Battle,
  },
  {
    characterId: 114,
    statusType: StatusType.God,
    rarity: Rarity.SuperRare,
    fileName: 'f361',
    cardType: CartType.Battle,
  },
  {
    characterId: 114,
    statusType: StatusType.Magica,
    rarity: Rarity.SuperRare,
    fileName: 'f362',
    cardType: CartType.Battle,
  },
  {
    characterId: 114,
    statusType: StatusType.Balance,
    rarity: Rarity.UltraRare,
    fileName: 'f363',
    cardType: CartType.Battle,
  },
  {
    characterId: 114,
    statusType: StatusType.God,
    rarity: Rarity.LegendRare,
    fileName: 'f364',
    cardType: CartType.Battle,
  },
  {
    characterId: 115,
    statusType: StatusType.Balance,
    rarity: Rarity.Common,
    fileName: 'f365',
    cardType: CartType.Battle,
  },
  {
    characterId: 115,
    statusType: StatusType.Power,
    rarity: Rarity.Rare,
    fileName: 'f366',
    cardType: CartType.Battle,
  },
  {
    characterId: 116,
    statusType: StatusType.Balance,
    rarity: Rarity.Common,
    fileName: 'f367',
    cardType: CartType.Battle,
  },
  {
    characterId: 116,
    statusType: StatusType.Speeder,
    rarity: Rarity.Rare,
    fileName: 'f368',
    cardType: CartType.Battle,
  },
  {
    characterId: 116,
    statusType: StatusType.Speeder,
    rarity: Rarity.UltraRare,
    fileName: 'f370',
    cardType: CartType.Battle,
  },
  {
    characterId: 116,
    statusType: StatusType.Balance,
    rarity: Rarity.Uncommon,
    fileName: 'f369',
    cardType: CartType.Battle,
  },
];
