export interface DungeonData {
  id: number;
  jaName: string;
  enName: string;
  imgFileNmae: string;
  urlRef: string;
}

export const DUNGEON_DATA: DungeonData[] = [
  {
    id: 1,
    jaName: '光の領域',
    enName: 'Area of light',
    imgFileNmae: 'd001.png',
    urlRef: 'http://maho-deco.com/material/gallery_bg.html',
  },
  {
    id: 2,
    jaName: '夜の丘',
    enName: 'Night hill',
    imgFileNmae: 'd002.png',
    urlRef: 'http://maho-deco.com/material/gallery_bg.html',
  },
  {
    id: 3,
    jaName: '平原1',
    enName: 'Plain 1',
    imgFileNmae: 'd003.png',
    urlRef: 'http://maho-deco.com/material/gallery_bg.html',
  },
  {
    id: 4,
    jaName: '平原2',
    enName: 'Plain 2',
    imgFileNmae: 'd004.png',
    urlRef: 'http://maho-deco.com/material/gallery_bg.html',
  },
  {
    id: 5,
    jaName: '平原3',
    enName: 'Plain 3',
    imgFileNmae: 'd005.png',
    urlRef: 'http://maho-deco.com/material/gallery_bg.html',
  },
  {
    id: 6,
    jaName: '断崖の街',
    enName: 'Cliff town',
    imgFileNmae: 'd006.png',
    urlRef: 'http://maho-deco.com/material/gallery_bg.html',
  },
  {
    id: 7,
    jaName: '森',
    enName: 'Woods',
    imgFileNmae: 'd007.png',
    urlRef: 'http://maho-deco.com/material/gallery_bg.html',
  },
  {
    id: 8,
    jaName: '森の遺跡',
    enName: 'Ruins of the forest',
    imgFileNmae: 'd008.png',
    urlRef: 'http://maho-deco.com/material/gallery_bg.html',
  },
  {
    id: 9,
    jaName: '水晶洞窟',
    enName: 'Crystal cave',
    imgFileNmae: 'd009.png',
    urlRef: 'http://maho-deco.com/material/gallery_bg.html',
  },
  {
    id: 10,
    jaName: '氷の領域',
    enName: 'Ice area',
    imgFileNmae: 'd010.png',
    urlRef: 'http://maho-deco.com/material/gallery_bg.html',
  },
  {
    id: 11,
    jaName: '洞窟',
    enName: 'cave',
    imgFileNmae: 'd011.png',
    urlRef: 'http://maho-deco.com/material/gallery_bg.html',
  },
  {
    id: 12,
    jaName: '洞窟2',
    enName: 'cave 2',
    imgFileNmae: 'd012.png',
    urlRef: 'http://maho-deco.com/material/gallery_bg.html',
  },
  {
    id: 13,
    jaName: '火山',
    enName: 'Volcano',
    imgFileNmae: 'd013.png',
    urlRef: 'http://maho-deco.com/material/gallery_bg.html',
  },
  {
    id: 14,
    jaName: '神殿',
    enName: 'temple',
    imgFileNmae: 'd014.png',
    urlRef: 'http://maho-deco.com/material/gallery_bg.html',
  },
  {
    id: 15,
    jaName: '街',
    enName: 'Town',
    imgFileNmae: 'd015.png',
    urlRef: 'http://maho-deco.com/material/gallery_bg.html',
  },
  {
    id: 16,
    jaName: '街道',
    enName: 'highway',
    imgFileNmae: 'd016.png',
    urlRef: 'http://maho-deco.com/material/gallery_bg.html',
  },
  {
    id: 17,
    jaName: '闇の神殿',
    enName: 'Temple of Darkness',
    imgFileNmae: 'd017.png',
    urlRef: 'http://maho-deco.com/material/gallery_bg.html',
  },
];

export const DUNGEON_DATA2: DungeonData[] = [
  {
    id: 1,
    jaName: '岩場',
    enName: 'Rocky place',
    imgFileNmae: 'd001.jpg',
    urlRef: 'https://k-after.at.webry.info/200806/article_9.html',
  },
  {
    id: 2,
    jaName: '洞窟',
    enName: 'cave',
    imgFileNmae: 'd002.png',
    urlRef:
      'http://teddy-plaza.sakura.ne.jp/wp/wp-content/uploads/2016/07/158e35945dfb441ed15105ed7c0e7849.png',
  },
  {
    id: 3,
    jaName: '暖かい島の海岸(昼間)',
    enName: 'Warm island coast (daytime)',
    imgFileNmae: 'd003.jpg',
    urlRef: 'https://k-after.at.webry.info/200806/article_11.html',
  },
  {
    id: 4,
    jaName: '暖かい島の海岸(夕暮れ)',
    enName: 'Warm island coast (dusk)',
    imgFileNmae: 'd004.jpg',
    urlRef: 'https://k-after.at.webry.info/200806/article_11.html',
  },
  {
    id: 5,
    jaName: '暖かい島の海岸(夜)',
    enName: 'Warm island coast (night)',
    imgFileNmae: 'd005.jpg',
    urlRef: 'https://k-after.at.webry.info/200806/article_11.html',
  },
  {
    id: 6,
    jaName: '森の道(昼)',
    enName: 'Forest Road (Day)',
    imgFileNmae: 'd006.jpg',
    urlRef: 'https://k-after.at.webry.info/200806/article_10.html',
  },
  {
    id: 7,
    jaName: '森の道(夕方)',
    enName: 'Forest Road (Evening)',
    imgFileNmae: 'd007.jpg',
    urlRef: 'https://k-after.at.webry.info/200806/article_10.html',
  },
  {
    id: 8,
    jaName: '森の道(夜)',
    enName: 'Forest Road (Night)',
    imgFileNmae: 'd008.jpg',
    urlRef: 'https://k-after.at.webry.info/200806/article_10.html',
  },
  {
    id: 9,
    jaName: '森の入り口',
    enName: 'Forest entrance',
    imgFileNmae: 'd009.jpg',
    urlRef: 'https://k-after.at.webry.info/200806/article_3.html',
  },
  {
    id: 10,
    jaName: '森の茂み',
    enName: 'Forest bush',
    imgFileNmae: 'd010.jpg',
    urlRef: 'https://k-after.at.webry.info/200806/article_3.html',
  },
  {
    id: 11,
    jaName: '森の小川(昼)',
    enName: 'Forest stream (Day)',
    imgFileNmae: 'd011.jpg',
    urlRef: 'https://k-after.at.webry.info/200806/article_8.html',
  },
  {
    id: 12,
    jaName: '森の小川(夕方)',
    enName: 'Forest stream (Evening)',
    imgFileNmae: 'd012.jpg',
    urlRef: 'https://k-after.at.webry.info/200806/article_8.html',
  },
  {
    id: 13,
    jaName: '森の小川(夜)',
    enName: 'Forest stream (Night)',
    imgFileNmae: 'd013.jpg',
    urlRef: 'https://k-after.at.webry.info/200806/article_8.html',
  },
  {
    id: 14,
    jaName: '清流の水源(昼)',
    enName: 'Clear water source (Day)',
    imgFileNmae: 'd014.jpg',
    urlRef: 'https://k-after.at.webry.info/200806/article_6.html',
  },
  {
    id: 15,
    jaName: '清流の水源(夕方)',
    enName: 'Clear water source (Evening)',
    imgFileNmae: 'd015.jpg',
    urlRef: 'https://k-after.at.webry.info/200806/article_6.html',
  },
  {
    id: 16,
    jaName: '清流の水源(夜)',
    enName: 'Clear water source (Night)',
    imgFileNmae: 'd016.jpg',
    urlRef: 'https://k-after.at.webry.info/200806/article_6.html',
  },
  {
    id: 17,
    jaName: '森のせせらぎ(昼)',
    enName: 'Forest murmuring (Day)',
    imgFileNmae: 'd017.jpg',
    urlRef: 'https://k-after.at.webry.info/200806/article_7.html',
  },
  {
    id: 18,
    jaName: '森のせせらぎ(夕方)',
    enName: 'Forest murmuring (Evening)',
    imgFileNmae: 'd018.jpg',
    urlRef: 'https://k-after.at.webry.info/200806/article_7.html',
  },
  {
    id: 19,
    jaName: '森のせせらぎ(夜)',
    enName: 'Forest murmuring (Night)',
    imgFileNmae: 'd019.jpg',
    urlRef: 'https://k-after.at.webry.info/200806/article_7.html',
  },
  {
    id: 20,
    jaName: '森の小橋(昼)',
    enName: 'Forest bridge (Day)',
    imgFileNmae: 'd020.jpg',
    urlRef: 'https://k-after.at.webry.info/200806/article_5.html',
  },
  {
    id: 21,
    jaName: '森の小橋(夕方)',
    enName: 'Forest bridge (Evening)',
    imgFileNmae: 'd021.jpg',
    urlRef: 'https://k-after.at.webry.info/200806/article_5.html',
  },
  {
    id: 22,
    jaName: '森の小橋(夜)',
    enName: 'Forest bridge (Night)',
    imgFileNmae: 'd022.jpg',
    urlRef: 'https://k-after.at.webry.info/200806/article_5.html',
  },
  {
    id: 22,
    jaName: '森の小橋(夜)',
    enName: 'Forest bridge (Night)',
    imgFileNmae: 'd022.jpg',
    urlRef: 'https://k-after.at.webry.info/200806/article_5.html',
  },
  {
    id: 23,
    jaName: '街道',
    enName: 'highway',
    imgFileNmae: 'd023.jpg',
    urlRef: 'https://k-after.at.webry.info/201712/article_3.html',
  },
  {
    id: 24,
    jaName: 'コントロールルーム',
    enName: 'Control room',
    imgFileNmae: 'd024.jpg',
    urlRef: 'https://winddorf.net/archives/04050901.html',
  },
  {
    id: 25,
    jaName: '岩石洞窟',
    enName: 'Rock cave',
    imgFileNmae: 'd025.jpg',
    urlRef: 'http://moonwind.pw/material/graphics/nature/earth/other/01.html',
  },
  {
    id: 26,
    jaName: '月下のフロア',
    enName: 'Marble floor illuminated by moonlight',
    imgFileNmae: 'd026.jpg',
    urlRef: 'https://www.pixiv.net/artworks/26544316',
  },
  {
    id: 27,
    jaName: '星空に照らされる採掘跡地',
    enName: 'Marble floor illuminated by moonlight',
    imgFileNmae: 'd027.jpg',
    urlRef: 'https://www.pixiv.net/artworks/56799440',
  },
  {
    id: 28,
    jaName: 'レンガのフロア',
    enName: 'Brick floor',
    imgFileNmae: 'd028.jpg',
    urlRef: 'https://www.pixiv.net/artworks/58762965',
  },
  {
    id: 29,
    jaName: '水の洞窟',
    enName: 'Water cave',
    imgFileNmae: 'd029.jpg',
    urlRef: 'https://www.pixiv.net/artworks/76306258',
  },
  {
    id: 30,
    jaName: '薄暗い洞窟',
    enName: 'Dim cave',
    imgFileNmae: 'd030.jpg',
    urlRef: 'https://www.pixiv.net/artworks/76306258',
  },
  {
    id: 31,
    jaName: 'ドラゴンの体内',
    enName: 'Inside the dragon body',
    imgFileNmae: 'd031.jpg',
    urlRef: 'https://www.pixiv.net/artworks/76306258',
  },
  {
    id: 32,
    jaName: '紅葉の間',
    enName: 'A room with colorful leaves',
    imgFileNmae: 'd032.jpg',
    urlRef: 'https://www.pixiv.net/artworks/76419627',
  },
  {
    id: 33,
    jaName: '新緑の間',
    enName: 'Room with fresh green',
    imgFileNmae: 'd033.jpg',
    urlRef: 'https://www.pixiv.net/artworks/76419627',
  },
  {
    id: 34,
    jaName: '紅に染まる部屋',
    enName: 'Room dyed red',
    imgFileNmae: 'd034.jpg',
    urlRef: 'https://www.pixiv.net/artworks/76419627',
  },
  {
    id: 35,
    jaName: '水晶の洞窟',
    enName: 'Crystal cave',
    imgFileNmae: 'd035.jpg',
    urlRef: 'https://www.pixiv.net/artworks/56451337',
  },
  {
    id: 36,
    jaName: '侍達の戦跡',
    enName: 'Battlefield of Samurai',
    imgFileNmae: 'd036.jpg',
    urlRef: 'https://www.pixiv.net/artworks/56936318',
  },
  {
    id: 37,
    jaName: '洞窟の入り口',
    enName: 'Cave entrance',
    imgFileNmae: 'd037.jpg',
    urlRef: 'https://www.pixiv.net/artworks/52792051',
  },
  {
    id: 38,
    jaName: '深き森',
    enName: 'Deep forest',
    imgFileNmae: 'd038.jpg',
    urlRef: 'https://www.pixiv.net/artworks/52792051',
  },
  {
    id: 39,
    jaName: '森',
    enName: 'Forest',
    imgFileNmae: 'd039.jpg',
    urlRef: 'https://www.pixiv.net/artworks/42660120',
  },
  {
    id: 40,
    jaName: '森の泉',
    enName: 'Forest fountain',
    imgFileNmae: 'd040.jpg',
    urlRef: 'https://www.pixiv.net/artworks/76232890',
  },
  {
    id: 41,
    jaName: '汚れた沼',
    enName: 'Dirty swamp',
    imgFileNmae: 'd041.jpg',
    urlRef: 'https://www.pixiv.net/artworks/76232890',
  },
  {
    id: 42,
    jaName: '幻の花草原',
    enName: 'Phantom flower meadow',
    imgFileNmae: 'd042.jpg',
    urlRef: 'https://www.pixiv.net/artworks/25666285',
  },
  {
    id: 43,
    jaName: '鍾乳洞',
    enName: 'Limestone cave',
    imgFileNmae: 'd043.jpg',
    urlRef: 'https://www.pixiv.net/artworks/23017273',
  },
  {
    id: 44,
    jaName: '森',
    enName: 'Forest',
    imgFileNmae: 'd044.jpg',
    urlRef: 'https://www.pixiv.net/artworks/53190914',
  },
  {
    id: 45,
    jaName: '森',
    enName: 'Forest road',
    imgFileNmae: 'd045.jpg',
    urlRef: 'https://www.pixiv.net/artworks/59817456',
  },
  {
    id: 46,
    jaName: '秋の林',
    enName: 'Autumn forest',
    imgFileNmae: 'd046.jpg',
    urlRef: 'https://www.pixiv.net/artworks/59817456',
  },
  {
    id: 47,
    jaName: '霊の住むフロア',
    enName: 'The floor where the spirit lives',
    imgFileNmae: 'd047.jpg',
    urlRef: 'https://www.pixiv.net/artworks/59817456',
  },
  {
    id: 48,
    jaName: '洋館',
    enName: 'Western-style building',
    imgFileNmae: 'd048.jpg',
    urlRef: 'https://www.pixiv.net/artworks/38402091',
  },
  {
    id: 49,
    jaName: '溶岩洞窟',
    enName: 'Lava cave',
    imgFileNmae: 'd049.jpg',
    urlRef: 'https://www.pixiv.net/artworks/26547085',
  },
  {
    id: 50,
    jaName: '夜の海沿いの崖',
    enName: 'Seaside cliffs at night',
    imgFileNmae: 'd050.jpg',
    urlRef: 'https://www.pixiv.net/artworks/76617965',
  },
  {
    id: 51,
    jaName: '雪山',
    enName: 'Snow mountain',
    imgFileNmae: 'd051.jpg',
    urlRef: 'https://www.pixiv.net/artworks/76585037',
  },
  {
    id: 52,
    jaName: '岩山の街',
    enName: 'Rocky town',
    imgFileNmae: 'd052.jpg',
    urlRef: 'https://www.pixiv.net/artworks/76942701',
  },
  {
    id: 53,
    jaName: '湖のある公園(昼)',
    enName: 'Park with lake (daytime)',
    imgFileNmae: 'd053.jpg',
    urlRef: 'https://www.pixiv.net/artworks/13365257',
  },
  {
    id: 54,
    jaName: '湖のある公園(夕方)',
    enName: 'Park with lake (evening)',
    imgFileNmae: 'd054.jpg',
    urlRef: 'https://www.pixiv.net/artworks/13365257',
  },
  {
    id: 55,
    jaName: '湖のある公園(夜)',
    enName: 'Park with lake (night)',
    imgFileNmae: 'd055.jpg',
    urlRef: 'https://www.pixiv.net/artworks/13365257',
  },
  {
    id: 56,
    jaName: '湖のある公園(昼曇り)',
    enName: 'Park with lake (cloudy day)',
    imgFileNmae: 'd056.jpg',
    urlRef: 'https://www.pixiv.net/artworks/13365257',
  },
  {
    id: 57,
    jaName: '湖のある公園(昼雨なし)',
    enName: 'Park with lake (no daytime rain)',
    imgFileNmae: 'd057.jpg',
    urlRef: 'https://www.pixiv.net/artworks/13365257',
  },
  {
    id: 58,
    jaName: '湖のある公園(昼雨)',
    enName: 'Park with a lake (daytime rain)',
    imgFileNmae: 'd058.jpg',
    urlRef: 'https://www.pixiv.net/artworks/13365257',
  },
  {
    id: 59,
    jaName: '田舎の県道',
    enName: 'Country road',
    imgFileNmae: 'd059.jpg',
    urlRef: 'https://www.pixiv.net/artworks/72849752',
  },
  {
    id: 60,
    jaName: '森の入り口',
    enName: 'Forest entrance',
    imgFileNmae: 'd060.jpg',
    urlRef: 'https://www.pixiv.net/artworks/36019058',
  },
  {
    id: 61,
    jaName: '森の泉',
    enName: 'Forest fountain',
    imgFileNmae: 'd061.jpg',
    urlRef: 'https://www.pixiv.net/artworks/31378664',
  },
  {
    id: 62,
    jaName: '森の小道',
    enName: 'Forest path',
    imgFileNmae: 'd062.jpg',
    urlRef: 'https://www.pixiv.net/artworks/73369312',
  },
  {
    id: 63,
    jaName: '夜桜',
    enName: 'Cherry blossoms at night',
    imgFileNmae: 'd063.jpg',
    urlRef: 'https://www.pixiv.net/artworks/18073647',
  },
  {
    id: 64,
    jaName: '精霊の住む森',
    enName: 'Forest where spirits live',
    imgFileNmae: 'd064.jpg',
    urlRef: 'https://www.pixiv.net/artworks/56936245',
  },
  {
    id: 65,
    jaName: '湿地帯',
    enName: 'Swamp',
    imgFileNmae: 'd065.jpg',
    urlRef: 'https://www.pixiv.net/artworks/6435057',
  },
  {
    id: 66,
    jaName: '山',
    enName: 'Mountain',
    imgFileNmae: 'd066.jpg',
    urlRef: 'https://www.pixiv.net/artworks/76807672',
  },
  {
    id: 67,
    jaName: '市松の床',
    enName: 'Checkered floor',
    imgFileNmae: 'd067.jpg',
    urlRef: 'https://www.pixiv.net/artworks/19436227',
  },
  {
    id: 68,
    jaName: '草原',
    enName: 'Meadow',
    imgFileNmae: 'd068.jpg',
    urlRef: 'https://www.pixiv.net/artworks/77611757',
  },
  {
    id: 69,
    jaName: '終わらない廊下',
    enName: 'A never ending corridor',
    imgFileNmae: 'd069.jpg',
    urlRef: 'https://www.pixiv.net/artworks/77611757',
  },
  {
    id: 70,
    jaName: '地底の太陽',
    enName: 'Underground sun',
    imgFileNmae: 'd070.jpg',
    urlRef: 'https://www.pixiv.net/artworks/29229575',
  },
  {
    id: 70,
    jaName: '地底の太陽',
    enName: 'Underground sun',
    imgFileNmae: 'd070.jpg',
    urlRef: 'https://www.pixiv.net/artworks/29229575',
  },
  {
    id: 71,
    jaName: '朝靄がかかる森',
    enName: 'Forest where the morning mist hangs',
    imgFileNmae: 'd071.jpg',
    urlRef: 'https://www.pixiv.net/artworks/930107',
  },
  {
    id: 72,
    jaName: '大空のフロア',
    enName: 'Sky floor',
    imgFileNmae: 'd072.jpg',
    urlRef: 'https://www.pixiv.net/artworks/57589547',
  },
];
