export interface DungeonData {
  id: number;
  jaName: string;
  enName: string;
  imgFileNmae: string;
  urlRef: string;
}

export const DUNGEON_DATA: DungeonData[] = [
  {
    id: 1,
    jaName: '岩場',
    enName: 'Rocky place',
    imgFileNmae: 'd001.jpg',
    urlRef: 'https://k-after.at.webry.info/200806/article_9.html',
  },
  {
    id: 2,
    jaName: '洞窟',
    enName: 'cave',
    imgFileNmae: 'd002.png',
    urlRef:
      'http://teddy-plaza.sakura.ne.jp/wp/wp-content/uploads/2016/07/158e35945dfb441ed15105ed7c0e7849.png',
  },
  {
    id: 3,
    jaName: '暖かい島の海岸(昼間)',
    enName: 'Warm island coast (daytime)',
    imgFileNmae: 'd003.jpg',
    urlRef: 'https://k-after.at.webry.info/200806/article_11.html',
  },
  {
    id: 4,
    jaName: '暖かい島の海岸(夕暮れ)',
    enName: 'Warm island coast (dusk)',
    imgFileNmae: 'd004.jpg',
    urlRef: 'https://k-after.at.webry.info/200806/article_11.html',
  },
  {
    id: 5,
    jaName: '暖かい島の海岸(夜)',
    enName: 'Warm island coast (night)',
    imgFileNmae: 'd005.jpg',
    urlRef: 'https://k-after.at.webry.info/200806/article_11.html',
  },
  {
    id: 6,
    jaName: '森の道(昼)',
    enName: 'Forest Road (Day)',
    imgFileNmae: 'd006.jpg',
    urlRef: 'https://k-after.at.webry.info/200806/article_10.html',
  },
  {
    id: 7,
    jaName: '森の道(夕方)',
    enName: 'Forest Road (Evening)',
    imgFileNmae: 'd007.jpg',
    urlRef: 'https://k-after.at.webry.info/200806/article_10.html',
  },
  {
    id: 8,
    jaName: '森の道(夜)',
    enName: 'Forest Road (Night)',
    imgFileNmae: 'd008.jpg',
    urlRef: 'https://k-after.at.webry.info/200806/article_10.html',
  },
  {
    id: 9,
    jaName: '森の入り口',
    enName: 'Forest entrance',
    imgFileNmae: 'd009.jpg',
    urlRef: 'https://k-after.at.webry.info/200806/article_3.html',
  },
  {
    id: 10,
    jaName: '森の茂み',
    enName: 'Forest bush',
    imgFileNmae: 'd010.jpg',
    urlRef: 'https://k-after.at.webry.info/200806/article_3.html',
  },
  {
    id: 11,
    jaName: '森の小川(昼)',
    enName: 'Forest stream (Day)',
    imgFileNmae: 'd011.jpg',
    urlRef: 'https://k-after.at.webry.info/200806/article_8.html',
  },
  {
    id: 12,
    jaName: '森の小川(夕方)',
    enName: 'Forest stream (Evening)',
    imgFileNmae: 'd012.jpg',
    urlRef: 'https://k-after.at.webry.info/200806/article_8.html',
  },
  {
    id: 13,
    jaName: '森の小川(夜)',
    enName: 'Forest stream (Night)',
    imgFileNmae: 'd013.jpg',
    urlRef: 'https://k-after.at.webry.info/200806/article_8.html',
  },
  {
    id: 14,
    jaName: '清流の水源(昼)',
    enName: 'Clear water source (Day)',
    imgFileNmae: 'd014.jpg',
    urlRef: 'https://k-after.at.webry.info/200806/article_6.html',
  },
  {
    id: 15,
    jaName: '清流の水源(夕方)',
    enName: 'Clear water source (Evening)',
    imgFileNmae: 'd015.jpg',
    urlRef: 'https://k-after.at.webry.info/200806/article_6.html',
  },
  {
    id: 16,
    jaName: '清流の水源(夜)',
    enName: 'Clear water source (Night)',
    imgFileNmae: 'd016.jpg',
    urlRef: 'https://k-after.at.webry.info/200806/article_6.html',
  },
  {
    id: 17,
    jaName: '森のせせらぎ(昼)',
    enName: 'Forest murmuring (Day)',
    imgFileNmae: 'd017.jpg',
    urlRef: 'https://k-after.at.webry.info/200806/article_7.html',
  },
  {
    id: 18,
    jaName: '森のせせらぎ(夕方)',
    enName: 'Forest murmuring (Evening)',
    imgFileNmae: 'd018.jpg',
    urlRef: 'https://k-after.at.webry.info/200806/article_7.html',
  },
  {
    id: 19,
    jaName: '森のせせらぎ(夜)',
    enName: 'Forest murmuring (Night)',
    imgFileNmae: 'd019.jpg',
    urlRef: 'https://k-after.at.webry.info/200806/article_7.html',
  },
  {
    id: 20,
    jaName: '森の小橋(昼)',
    enName: 'Forest bridge (Day)',
    imgFileNmae: 'd020.jpg',
    urlRef: 'https://k-after.at.webry.info/200806/article_5.html',
  },
  {
    id: 21,
    jaName: '森の小橋(夕方)',
    enName: 'Forest bridge (Evening)',
    imgFileNmae: 'd021.jpg',
    urlRef: 'https://k-after.at.webry.info/200806/article_5.html',
  },
  {
    id: 22,
    jaName: '森の小橋(夜)',
    enName: 'Forest bridge (Night)',
    imgFileNmae: 'd022.jpg',
    urlRef: 'https://k-after.at.webry.info/200806/article_5.html',
  },
  {
    id: 22,
    jaName: '森の小橋(夜)',
    enName: 'Forest bridge (Night)',
    imgFileNmae: 'd022.jpg',
    urlRef: 'https://k-after.at.webry.info/200806/article_5.html',
  },
  {
    id: 23,
    jaName: '街道',
    enName: 'highway',
    imgFileNmae: 'd023.jpg',
    urlRef: 'https://k-after.at.webry.info/201712/article_3.html',
  },
  {
    id: 24,
    jaName: 'コントロールルーム',
    enName: 'Control room',
    imgFileNmae: 'd024.jpg',
    urlRef: 'https://winddorf.net/archives/04050901.html',
  },
  {
    id: 25,
    jaName: '岩石洞窟',
    enName: 'Rock cave',
    imgFileNmae: 'd025.jpg',
    urlRef: 'http://moonwind.pw/material/graphics/nature/earth/other/01.html',
  },
  {
    id: 26,
    jaName: '月下のフロア',
    enName: 'Marble floor illuminated by moonlight',
    imgFileNmae: 'd026.jpg',
    urlRef: 'https://www.pixiv.net/artworks/26544316',
  },
  {
    id: 27,
    jaName: '星空に照らされる採掘跡地',
    enName: 'Marble floor illuminated by moonlight',
    imgFileNmae: 'd027.jpg',
    urlRef: 'https://www.pixiv.net/artworks/56799440',
  },
  {
    id: 28,
    jaName: 'レンガのフロア',
    enName: 'Brick floor',
    imgFileNmae: 'd028.jpg',
    urlRef: 'https://www.pixiv.net/artworks/58762965',
  },
  {
    id: 29,
    jaName: '水の洞窟',
    enName: 'Water cave',
    imgFileNmae: 'd029.jpg',
    urlRef: 'https://www.pixiv.net/artworks/76306258',
  },
  {
    id: 30,
    jaName: '薄暗い洞窟',
    enName: 'Dim cave',
    imgFileNmae: 'd030.jpg',
    urlRef: 'https://www.pixiv.net/artworks/76306258',
  },
  {
    id: 31,
    jaName: 'ドラゴンの体内',
    enName: 'Inside the dragon body',
    imgFileNmae: 'd031.jpg',
    urlRef: 'https://www.pixiv.net/artworks/76306258',
  },
  {
    id: 32,
    jaName: '紅葉の間',
    enName: 'A room with colorful leaves',
    imgFileNmae: 'd032.jpg',
    urlRef: 'https://www.pixiv.net/artworks/76419627',
  },
  {
    id: 33,
    jaName: '新緑の間',
    enName: 'Room with fresh green',
    imgFileNmae: 'd033.jpg',
    urlRef: 'https://www.pixiv.net/artworks/76419627',
  },
  {
    id: 34,
    jaName: '紅に染まる部屋',
    enName: 'Room dyed red',
    imgFileNmae: 'd034.jpg',
    urlRef: 'https://www.pixiv.net/artworks/76419627',
  },
  {
    id: 35,
    jaName: '水晶の洞窟',
    enName: 'Crystal cave',
    imgFileNmae: 'd035.jpg',
    urlRef: 'https://www.pixiv.net/artworks/56451337',
  },
  {
    id: 36,
    jaName: '侍達の戦跡',
    enName: 'Battlefield of Samurai',
    imgFileNmae: 'd036.jpg',
    urlRef: 'https://www.pixiv.net/artworks/56936318',
  },
  {
    id: 37,
    jaName: '洞窟の入り口',
    enName: 'Cave entrance',
    imgFileNmae: 'd037.jpg',
    urlRef: 'https://www.pixiv.net/artworks/52792051',
  },
  {
    id: 38,
    jaName: '深き森',
    enName: 'Deep forest',
    imgFileNmae: 'd038.jpg',
    urlRef: 'https://www.pixiv.net/artworks/52792051',
  },
  {
    id: 39,
    jaName: '森',
    enName: 'Forest',
    imgFileNmae: 'd039.jpg',
    urlRef: 'https://www.pixiv.net/artworks/42660120',
  },
  {
    id: 40,
    jaName: '森の泉',
    enName: 'Forest fountain',
    imgFileNmae: 'd040.jpg',
    urlRef: 'https://www.pixiv.net/artworks/76232890',
  },
  {
    id: 41,
    jaName: '汚れた沼',
    enName: 'Dirty swamp',
    imgFileNmae: 'd041.jpg',
    urlRef: 'https://www.pixiv.net/artworks/76232890',
  },
  {
    id: 42,
    jaName: '幻の花草原',
    enName: 'Phantom flower meadow',
    imgFileNmae: 'd042.jpg',
    urlRef: 'https://www.pixiv.net/artworks/25666285',
  },
  {
    id: 43,
    jaName: '鍾乳洞',
    enName: 'Limestone cave',
    imgFileNmae: 'd043.jpg',
    urlRef: 'https://www.pixiv.net/artworks/23017273',
  },
  {
    id: 44,
    jaName: '森',
    enName: 'Forest',
    imgFileNmae: 'd044.jpg',
    urlRef: 'https://www.pixiv.net/artworks/53190914',
  },
  {
    id: 45,
    jaName: '森',
    enName: 'Forest road',
    imgFileNmae: 'd045.jpg',
    urlRef: 'https://www.pixiv.net/artworks/59817456',
  },
  {
    id: 46,
    jaName: '秋の林',
    enName: 'Autumn forest',
    imgFileNmae: 'd046.jpg',
    urlRef: 'https://www.pixiv.net/artworks/59817456',
  },
  {
    id: 47,
    jaName: '霊の住むフロア',
    enName: 'The floor where the spirit lives',
    imgFileNmae: 'd047.jpg',
    urlRef: 'https://www.pixiv.net/artworks/59817456',
  },
  {
    id: 48,
    jaName: '洋館',
    enName: 'Western-style building',
    imgFileNmae: 'd048.jpg',
    urlRef: 'https://www.pixiv.net/artworks/38402091',
  },
  {
    id: 49,
    jaName: '溶岩洞窟',
    enName: 'Lava cave',
    imgFileNmae: 'd049.jpg',
    urlRef: 'https://www.pixiv.net/artworks/26547085',
  },
];
